### ISSUE TITLE
When platform: clearos it's shows platform_family: blank

### ISSUE THREAD

**Issue by kmf** [chef/ohai#1002]
When detecting platform: clearos,  it should display platform_family: rhel currently it's blank.

**Comment by iennae** [comment]
It's not clear that it should be rhel based on some of the documentation we're reading. While I've created PR #1004, this might be a case that it's more like fedora than rhel.

**Comment by kmf** [comment]
https://github.com/clearos/clearos-release

Based on CentOS, info based on their release package.

**Comment by kmf** [comment]
https://github.com/clearos/kernel... Kernel forked from CentOS

**Comment by tas50** [comment]
This has been resolved on master and will ship in Ohai 13.2
