### ISSUE TITLE
AIX RPM packages have the version embedded in the package name

### ISSUE THREAD

**Issue by msgarbossa** [chef/ohai#1015]
## Description

Ohai on AIX uses "lslpp -L -q -c" to capture package information on all package types, including LPP and RPM.

The LPPs are stored as expected:
    "bos.rte": {
      "version": "7.1.3.45"
    },
    
RPMs are stored with the version embedded in the package name:
    "wget-1.9.1-3": {
      "version": "1.9.1-3"
    },

In order to check the version attribute of the wget RPM, the version would need to be known ahead of time or additional parsing would be needed to check if wget is installed.  This is happening because the lslpp command being used outputs in the following format:

#Package Name:Fileset:Level:State:PTF Id:Fix State:Type:Description:Destination Dir.:Uninstaller:Message Catalog:Message Set:Message Number:Parent:Automatic:

The issue is in https://github.com/chef/ohai/blob/master/lib/ohai/plugins/packages.rb.
For LPP packages, the 2nd field containing the fileset name is used and the 1st field is discarded.  For RPMs, the 2nd field should not be used and the 1st field containing the package name should be used.

## Ohai Version

13.1.0

## Platform Version

AIX

**Comment by tas50** [comment]
@msgarbossa Can you paste the output of `lslpp -L -q -c` where wget is so I can add this to our unit test.

**Comment by msgarbossa** [comment]
Output for wget (RPM) and bos.rte (LPP):
# lslpp -L -q -c | grep ^wget:
wget:wget-1.9.1-3:1.9.1-3: : :C:R:A utility for retrieving files using the HTTP or FTP protocols.: :/bin/rpm -e wget: : : : :0: :/opt/freeware:Wed Nov  5 01:37:09 MST 2014
# lslpp -L -q -c | grep :bos.rte:
bos:bos.rte:7.1.3.45: : :C: :Base Operating System Runtime: : : : : : :1:0:/:

**Comment by tas50** [comment]
The fix for this was just merged to master and will ship with Ohai/Chef 13.2. Thanks for the troubleshooting help
