### ISSUE TITLE
Ohai 8.24.0 doesnt detect virtualization correctly inside a container running on LXC over Proxmox

### ISSUE THREAD

**Issue by aalmenar** [chef/ohai#1026]
## Description

Running Ohai inside a LXC container running on proxmox returns incorrect variables on virtualization like:

  "virtualization": {
    "systems": {
      "kvm": "host"
    },
    "system": "kvm",
    "role": "host"
  },

## Ohai Version
8.24.0

## Platform Version
Debian 9.0

## Explanation
Checking the code here, https://github.com/chef/ohai/blob/ec980071ce34627701f039c0deae37022b4742d2/lib/ohai/plugins/linux/virtualization.rb#L181-L208

None of the checks find what is currently running is an lxc container, but found out the following:

$ cat /proc/1/environ | tr '\0' '\n' | grep ^container
container=lxc
container_ttys=/dev/pts/0 /dev/pts/1

It may help on those cases where there is not a cgroup indicating lxc:

The check may see this and thats why it's failing:

$ cat /proc/self/cgroup
11:cpuset:/
10:freezer:/
9:pids:/
8:hugetlb:/
7:devices:/
6:memory:/
5:net_cls,net_prio:/
4:blkio:/
3:cpu,cpuacct:/
2:perf_event:/
1:name=systemd:/

If anything is needed for further assistance, please dont hesitate to ask.

**Comment by aalmenar** [comment]
## Description
Ohai does not detect a host is able to run lxc containers especially a proxmox server.

## Ohai Version
8.24.0

## Platform Version
Proxmox 5.0

## Ohai Output
  "virtualization": {
    "systems": {
      "kvm": "host"
    },
    "system": "kvm",
    "role": "host"
  },

This does not include LXC as host. 

The code here https://github.com/chef/ohai/blob/ec980071ce34627701f039c0deae37022b4742d2/lib/ohai/plugins/linux/virtualization.rb#L189

Only checks for cgroup and if lxc-version command exists, which since version 1.0.0 beta3 has been removed (Althoug it still available on the LTS release of lxc).

This command has been replaced with:

$ lxc-start --version
2.0.8

And to prove there is a LXC running:

lxc-info --name 100
Name:           100
State:          RUNNING
PID:            17774
IP:             x.x.x.x
CPU use:        37.47 seconds
BlkIO use:      576.00 KiB
Memory use:     179.85 MiB
KMem use:       13.29 MiB
Link:           veth100i0
 TX bytes:      2.19 MiB
 RX bytes:      8.10 MiB
 Total bytes:   10.29 MiB

**Comment by aalmenar** [comment]
Tested both with ohai 13 as requested on #1027  and the issue is the same.

**Comment by mrala** [comment]
@aalmenar,  is this still an issue? It looks like there is now a check for `lxc-start`, in addition to `lxc-version`:

https://github.com/chef/ohai/blob/v13.7.0/lib/ohai/plugins/linux/virtualization.rb#L25

**Comment by tas50** [comment]
Closing this out since we haven't heard back about the new lxc detection. If this is still a problem in Ohai 13.7 feel free to open it back up and I'll see what we can do about improving that detection.
