### ISSUE TITLE
Ohai 8.24.0 doesn't detect virtualization correctly of a Host LXC using Proxmox as HV

### ISSUE THREAD

**Issue by aalmenar** [chef/ohai#1027]
## Description
Ohai does not detect a host is able to run lxc containers especially a proxmox server.

## Ohai Version
8.24.0

## Platform Version
Proxmox 5.0

## Ohai Output
  "virtualization": {
    "systems": {
      "kvm": "host"
    },
    "system": "kvm",
    "role": "host"
  },

This does not include LXC as host. 

The code here https://github.com/chef/ohai/blob/ec980071ce34627701f039c0deae37022b4742d2/lib/ohai/plugins/linux/virtualization.rb#L189

Only checks for cgroup and if lxc-version command exists, which since version 1.0.0 beta3 has been removed (Althoug it still available on the LTS release of lxc).

This command has been replaced with:

$ lxc-start --version
2.0.8

And to prove there is a LXC running:

lxc-info --name 100
Name:           100
State:          RUNNING
PID:            17774
IP:             x.x.x.x
CPU use:        37.47 seconds
BlkIO use:      576.00 KiB
Memory use:     179.85 MiB
KMem use:       13.29 MiB
Link:           veth100i0
 TX bytes:      2.19 MiB
 RX bytes:      8.10 MiB
 Total bytes:   10.29 MiB

**Comment by thommay** [comment]
Can we close this issue and consolidate in #1026? Also, ohai 8 is now only receiving security and major bug fixes; please can you test with ohai 13 and see if the problem still exists - I imagine it does.

**Comment by aalmenar** [comment]
I understand, but this is the version available with omnibus chef-client download for chef 12. Not all opscode cookbooks work with chef 13.

**Comment by aalmenar** [comment]
BTW, tested with ohai 13 issue is the same:

ohai -v
Ohai: 13.2.0

**Comment by thommay** [comment]
since you mentioned it, which cookbooks are you having problems with on chef 13? Thanks for moving the info over to the other bug.

**Comment by aalmenar** [comment]
My mistake, it was other cookbooks from the supermarket.

**Comment by thommay** [comment]
ok, no problem. I'm gonna close this ticket now.

**Comment by aalmenar** [comment]
BTW. as a comment the cookbook that doesnt work with chef 13 is https://github.com/chef-cookbooks/mysql kitchen test fails but if set to 12 works flawlessly.
