### ISSUE TITLE
Incorrectly determined cloud provider

### ISSUE THREAD

**Issue by heaven** [chef/ohai#1062]
Our cluster is deployed to Digital Ocean (NY2), 24 nodes and 4 nodes detected as `ec2` instead of `digital_ocean`. This causes bugs in other cookbooks that rely on this data.

## Ohai Version
2.1.0 (I know it's old but we can't upgrade currently due to other dependencies)

## Platform Version
Ubuntu 14.04.5 LTS
Chef 12.8

## Ohai Output

Corrent data:
```ruby
{"public_ips"=>
  [{"ip_address"=>"***",
    "type"=>"public",
    "netmask"=>"255.255.224.0"}],
 "private_ips"=>
  [{"ip_address"=>"***",
    "type"=>"private",
    "netmask"=>"255.255.0.0"},
   {"ip_address"=>"***",
    "type"=>"private",
    "cidr"=>"128"},
   {"ip_address"=>"***",
    "type"=>"private",
    "cidr"=>"128"}],
 "public_ipv4"=>
  {"ip_address"=>"***",
   "type"=>"public",
   "netmask"=>"255.255.224.0"},
 "public_ipv6"=>nil,
 "local_ipv4"=>
  {"ip_address"=>"***",
   "type"=>"private",
   "netmask"=>"255.255.0.0"},
 "local_ipv6"=>
  {"ip_address"=>"***",
   "type"=>"private",
   "cidr"=>"128"},
 "public_hostname"=>nil,
 "provider"=>"digital_ocean"}
```

Incorrect data:
```ruby
{"provider"=>"ec2",
 "public_ips"=>[nil],
 "private_ips"=>[nil],
 "public_ipv4"=>nil,
 "public_hostname"=>nil,
 "local_ipv4"=>nil,
 "local_hostname"=>nil}
```

Both nodes are `Ubuntu 14.04.5 LTS` and both deployed to the same region.

Perhaps there's any way I can reset this data and tell ohai to check again?

**Comment by tas50** [comment]
@heaven Can you send me the output of ohai -l debug?

**Comment by heaven** [comment]
@tas50 [ohai-debug.json.zip](https://github.com/chef/ohai/files/1326363/ohai-debug.json.zip)

Also, noticed the gem version is 8.19.2

**Comment by tas50** [comment]
@heaven Can you try upgrading this node to Chef 13 and running it again? We've made a bunch of changes to EC2 and Digital Ocean detection that I'm fairly certain resolves this.

**Comment by tas50** [comment]
Closing this out since the code was reworked in later releases
