### ISSUE TITLE
uptime_seconds and uptime should match on AIX

### ISSUE THREAD

**Issue by sean-horn** [chef/ohai#1074]
## Description

On a given AIX system, the uptime_seconds and uptime do not match.

uptime_seconds in the following case should be 4630366, not 1503190745

```
uptime_seconds: 1503190745
uptime: 53 days 14 hours 12 minutes 46 seconds
```

Therefore, our uptime_seconds is actually just the elapsed_seconds on AIX, not the current time minus the elapsed seconds. This will ensure screens on Manage/Automate that use these attributes remain accurate.

## Ohai Version

13.4.x and up

## Platform Version

AIX 7.x

## Ohai Output

```
uptime_seconds: 1503190745
uptime: 53 days 14 hours 12 minutes 46 seconds
```

**Comment by thommay** [comment]
This is due to the work done in #1049 to handle uptimes greater than a year. @rmcleod8 do you have thoughts here?

**Comment by rmcleod8** [comment]
Ah totally my oversight. uptime_seconds in #1049 is set to epoch. :| 

I saw @sean-horn submitted a PR to fix but is now closed?

There was a requirement where I work to provide uptime in epoch, I'd be happy to add an additional field here for uptime_epoch(dont ask) and update uptime_seconds = elapsed

**Comment by thommay** [comment]
Yep, that sounds great

**Comment by rmcleod8** [comment]
@thommay @sean-horn submitted above PR to change uptime_seconds to reflect elapsed seconds. Looks like one of the travisCI configs is borked tho... https://travis-ci.org/chef/ohai/jobs/287800296

**Comment by tas50** [comment]
Closing this out since we've merged the fix. This will go out in the next ohai/chef release
