### ISSUE TITLE
Turn off Passwd plugin by default in Chef 14

### ISSUE THREAD

**Issue by lamont-granquist** [chef/ohai#1076]
It generates vastly more pain than its utility.

(this may require some engineering to support plugins that are off-by-default, but that needs to get done for 14)

**Comment by scalp42** [comment]
@lamont-granquist could you share the issue with the passwd plugin?

**Comment by MarkGibbons** [comment]
If a place authenticates via Active Directory using VAS, SSSD or Centrify there's an excellent chance of reporting many thousands of password users from every server.  None of the information reported is actually useful or really related to the node.  In my case the ohai data starts to approach 1M per server.

**Comment by scalp42** [comment]
I see @MarkGibbons, not an issue here but it totally makes sense.

Thanks for the insight 👍

**Comment by tas50** [comment]
This has been disabled by default now with a method to reenable it. We'll have additional documentation up on the docs site and information in the release notes once Chef/Ohai 14 comes out.
