### ISSUE TITLE
Ohai Hard Limit on Sessions

### ISSUE THREAD

**Issue by sean-horn** [chef/ohai#1089]
## Description

Support has seen a couple of the following issue lately. Over time, thousands of operating system login sessions can be started up and not registered as closed by systemd's logind, because presumably, the sessions are stuck open by a process that was not shut down. This can happen with monitoring logins and other kinds of periodic logins. For example: https://forums.fedoraforum.org/showthread.php?294134-User-sessions-not-are-not-ended

This condition rapidly leads to giant 1MB+ Chef Client requests with request failures back to the Chef Server and potentially Automate 1.x when the data-collector is being used.

Something very simple like this `loginctl.stdout.split("\n").first(5).each do |line|` in place of https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/sessions.rb#L33 could limit the potential damage. I understand we don't want to be patching for error conditions that need to be handled, but most systems shouldn't normally have more than 5-10 sessions going anyway.

## Ohai Version

8.23

## Platform Version

Any RHEL/CentOS 7.x

## Ohai Output

Thousands of sessions returned by the sessions plugin.

**Comment by bish0polis** [comment]
Can confirm this makes a HUGE difference on my RHEL7/chef-12.20.3 client.  I limited mine to  50:

```
# ohai | wc
 119853  209776 2431011
# ohai | grep session | wc -l
18728

--- /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/plugins/linux/sessions.rb~ 2017-04-30 17:10:46.000000000 -0400
+++ /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/plugins/linux/sessions.rb  2017-11-20 01:31:09.081548018 -0500
@@ -30,7 +30,7 @@
       sessions[:by_session] = Mash.new unless sessions[:by_session]
       sessions[:by_user] = Mash.new unless sessions[:by_user]

-      loginctl.stdout.split("\n").each do |line|
+      loginctl.stdout.split("\n").first(50).each do |line|
         session, uid, user, seat = line.split
         s = {
           "session" => session,

# ohai | grep session | wc -l
102
```

.. and my 413 error went away, this time.

Thanks for the excellent and searchable answer, Sean - for one contributing factor at least - and making my night.

**Comment by haidangwa** [comment]
Maybe a bit too obvious, but since no one mentioned it yet, I thought I'd throw out there. If you're not interested in tracking the linux session data in your node data, simply disable the `:Sessions` plugin.

**Comment by thommay** [comment]
we're going to disable the sessions plugin in Chef 14 by default: https://github.com/chef/chef-rfc/pull/289

**Comment by tas50** [comment]
Closing this out now since the solution we took for Chef 14 was to disable the Sessions plugin out of the box. It's been pretty problematic as this thread shows and it's something that most people probably don't need. There will be additional information in the release notes on how to enable it if it's necessary for users.
