### ISSUE TITLE
FIPS support of shard plugin

### ISSUE THREAD

**Issue by sonic0002** [chef/ohai#1092]
## Description

Should we change the digest algorithm from MD5 to something else to support FIPS?

## Ohai Version

ohai-8.25.0

## Platform Version

All Linux

## Ohai Output

Initially, the Chef client run output with FIPS enabled (**fips true** in **client.rb**) is:

> Starting Chef Client, version 12.12.13
> OpenSSL FIPS 140 mode enabled
> md5_dgst.c(75): OpenSSL internal error, assertion failed: Low level API call to digest MD5 forbidden in FIPS mode!  

Then we noticed that **shard** is a built-in plugin of Chef and it uses MD5 to generate the seed and it failed the OpenSSL assertion of FIPS compatable algorithms.

**Comment by tas50** [comment]
We've marked the shard plugin as optional which means out the box it won't load and this resolves the FIPS warnings
