### ISSUE TITLE
Docker for Mac update seems to have hosed Ohai virtualization system output.

### ISSUE THREAD

**Issue by dsalazar-carecloud** [chef/ohai#1110]
## Description

I updated my Mac's install of Docker for Mac to the newest version (Version 17.12.0-ce-mac46 (21698)) and now cookbooks that check for the virtualization type are failing because the run is yielding an empty object.

```
# ohai -d /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.16.0/lib/ohai/plugins/linux virtualization
{
  "systems": {

  }
}
```
After diving into the resulting container to investigate what could be the potential issue I discovered that the regular expression that ohai is using to set the virtualization type is failing to match the new value that the docker update is outputting into the proc cgroup file.  

```
# New line item signature post upgrade.
# 1:cpuset:/docker-ce/docker/ca7a16ceaa29533b73916748e18ad520721fffd0e0e997966e02174adbddea3d
cgroup_content =~ %r{^\d+:[^:]+:/[^/]+/(lxc|docker)-.+$}
```
I'm going to submit a pull request for a slight modification to the regular expression that should not interfere with the current setup and also support this new format.  

```
# cgroup_content =~ %r{^\d+:[^:]+:/[^/]+/(lxc|docker)-?.+$}
# ohai -d /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.16.0/lib/ohai/plugins/linux virtualization
{
  "systems": {
    "docker": "guest"
  },
  "system": "docker",
  "role": "guest"
}
```

Hopefully it's the correct solution.  Thank you.

## Ohai Version

ohai (8.16.0)

## Platform Version

Ubuntu 14.04

## Ohai Output
```
# ohai -d /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.16.0/lib/ohai/plugins/linux virtualization
{
  "systems": {

  }
}
```

**Comment by tas50** [comment]
@dsalazar-carecloud Can you give this a try on the latest Ohai. 8.16 is pretty old at this point and we've changed a lot of code since then.

**Comment by dsalazar-carecloud** [comment]
@tas50 sure I'll give that a go.  The regex does look the same though in the master branch.  I'll report on my findings as soon as I get some more information.

https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/virtualization.rb#L182-L183

**Comment by dsalazar-carecloud** [comment]
@tas50 here are my latest findings.
```
root@f42ff3da35bf:/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.2.0/lib/ohai/plugins/linux# ohai -v
Ohai: 13.2.0

root@f42ff3da35bf:/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.2.0/lib/ohai/plugins/linux# ohai -d /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.2.0/lib/ohai/plugins/linux virtualization
{
  "systems": {

  }
}
```

**Comment by tas50** [comment]
Fix shipped in 13.7.1

**Comment by dsalazar-carecloud** [comment]
Awesome sir, very appreciated.  Any way to apply this patch to the ~> 8.26 version of Ohai.  Mainly for us Chef 12 users?

**Comment by tas50** [comment]
If a PR is opened to bring this into Ohai 8 I'll merge that.

**Comment by dsalazar-carecloud** [comment]
Great news I'll get on that.  Appreciate it.

**Comment by dsalazar-carecloud** [comment]
Looks like someone got to it before I did #1118.  👍
