### ISSUE TITLE
Use similar logic in Azure that we use in EC2 for finding the best metadata endpoint

### ISSUE THREAD

**Issue by tas50** [chef/ohai#1159]
Depending on where you are in Azure there are varying levels of metadata endpoints available to you. We currently can't support the latest version due to this. We should instead move to the EC2 method where we have an array of known working versions and we use the latest one available to us. This would allow us to use the latest and greatest while still supporting things like government azure that's always a bit behind.

**Comment by zanecodes** [comment]
This would be great to have, since newer versions of the metadata endpoint have since added more available metadata, and needing to wait for the hardcoded API version to be bumped in the plugin is a pain.

**Comment by ctrlaltdel121** [comment]
Is there any way at all to change it to use a newer metadata? I'm struggling to find a solution other than copying all the azure logic to my own plugin and putting the data under `azure2` or something.

**Comment by tas50** [comment]
Fixed by https://github.com/chef/ohai/pull/1427 which needs additional testing and specs

**Comment by tas50** [comment]
This will ship in Ohai 16
