### ISSUE TITLE
Add backport of Softlayer cloud plugin fix to Ohai 13.8.x

### ISSUE THREAD

**Issue by sean-horn** [chef/ohai#1162]
## Description

In order to preserve functionality, Ohai 13.8.x should have a backport of  https://github.com/chef/ohai/pull/1155 and result in a stable release of Chef Client 13.8.x containing the updated Ohai code.

Customers running on Softlayer are missing this functionality right now

**Comment by sean-horn** [comment]
This should be covered in https://github.com/chef/ohai/pull/1157

**Comment by thommay** [comment]
Done!
