### ISSUE TITLE
Run ohai over ssh rather than locally

### ISSUE THREAD

**Issue by atheiman** [chef/ohai#1183]
Are there any efforts to run ohai on a remote system over ssh without installing Ruby and Ohai on the remote system? I havent looked into ohai thoroughly, but is there a point somewhere in the code where you could run commands ohai runs remotely rather than locally?

Maybe the difficulty here is that ohai modules dont necessarily just run a shell command and then parse the response. Some modules depend on information they get from other gems, so you'd have to wrap the shell commands they run to make them run remotely as well.

So I guess what I'm asking is, are there any similar projects that you all are aware of that get system info remotely without an agent installation?

**Comment by lamont-granquist** [comment]
No, it doesn't just execute commands, but opens up files, and issues DNS requests.  Proxying all those ruby APIs over ssh would be a massive amount of surgery. 

These kinds of questions are also not bug reports and are better asked over slack, stackoverflow or the mailing list (or paid support contracts, which would be the way to make a feature like this actually happen).
