### ISSUE TITLE
Ohai for GCE fails to get metadata if private DNS server is used

### ISSUE THREAD

**Issue by chakatz** [chef/ohai#1206]
## Description

Ohai for GCE fails to get metadata if non-default (private) DNS server is used.

## Ohai Version

Ohai: 14.1.3

## Platform Version

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

## Ohai Output

Using chef-shell:
```
chef (14.1.12)> node['cloud']
 => nil
```

Here is the "problem" line:
https://github.com/chef/ohai/blob/d444918c87581a73d68c4d6f3cdd47e4bd8c6065/lib/ohai/mixin/gce_metadata.rb#L24

GCE_METADATA_ADDR defaults to **"metadata.google.internal."**
When *resolve.conf* has the GCE internal DNS server set as the default DNS this works fine.
`nameserver 169.254.169.254`. That is the default setup.
However, we want to use our own DNS server and put our own server first in the order:
```
nameserver 8.8.8.8
nameserver 169.254.169.254
```
When we do this, Ohai cannot get metadata from the GCE Metadata Server.
(I am not using 8.8.8.8 but for reproducing the problem it will suffice.)

GCE also adds this line to */etc/hosts*:
`169.254.169.254 metadata.google.internal # Added by Google`
but that is no help because: **GCE_METADATA_ADDR = "metadata.google.internal."** with a trailing dot, and there is no **metadata.google.internal.**, with a trailing dot, in the hosts file.

I have tried to use a hint:
```
# cat /etc/chef/ohai/hints/gce.json
{
  "GCE_METADATA_ADDR": "169.254.169.254"
}
```
I can tell the hint is being read but it does not define 'GCE_METADATA_ADDR' so that it will supersede the definition in gce_metadata.rb.

Perhaps gce_metadata.rb can use an IP address like the EC2 and Azure mixin files do?
Perhaps I am not defining the hint properly?
Perhaps something is broken?
My workaround is to add this to the hosts file but that is not elegant and the default is that things are broken.
`169.254.169.254 metadata.google.internal.`

Thanks!

**Comment by tas50** [comment]
@chakatz Can you open a PR to change the plugin to use the IP instead of the DNS name? We use  the IPs for Azure and EC2 already and that seems like the easier fix here. Added bonus it removes the need to resolve the IP every time Ohai runs.

**Comment by tas50** [comment]
I'm reopening this since changing it out actually broke aws. We were relying on the name resolution to detect if we were on GCE or not. Removing that made Azure/AWS appear to be GCE. We'll have to rework our detection logic a bit to make this possible.

**Comment by tas50** [comment]
@nathenharvey did some work to change how we detect GCE systems that will allow us to change to using the IP address for metadata fetching. This will ship in Chef 15 in April and we may backport it to Chef 14 if it proves to be a stable change.

**Comment by tas50** [comment]
Closing this out since I think we resolved part of the problem here.
