### ISSUE TITLE
Filesystem plugin: Add "EncryptionStatus" to each volume on Windows

### ISSUE THREAD

**Issue by stuartpreston** [chef/ohai#1226]
## Description

On a Windows System (tested on Windows 10), the EncryptionStatus for a volume can be seen by inspecting the `win32-encryptablevolume` class in the `root/cimv2/security/MicrosoftVolumeEncryption` namespace or by executing the following PowerShell (full compatibility/module versions to be determined)
```
> (Get-BitlockerVolume -MountPoint "C:").VolumeStatus
FullyEncrypted
```
Using this information would enhance the `ohai filesystem` plugin output to look similar to the following:
```json
{
  "C:": {
    "kb_size": 511463911,
    "kb_available": 252410994,
    "kb_used": 259052917,
    "percent_used": 50,
    "mount": "C:",
    "fs_type": "ntfs",
    "volume_name": "",
    "encryption_status": "FullyEncrypted"
  }
}
```
The `encryption_status` field is the text representation of the ConversionStatus class from https://docs.microsoft.com/en-us/windows/desktop/secprov/getconversionstatus-win32-encryptablevolume#parameters:

Value | Meaning
-- | --
FullyDecrypted | For a standard hard drive (HDD), the volume is fully decrypted. For a hardware encrypted hard drive (EHDD), the volume is perpetually unlocked.
FullyEncrypted | For a standard hard drive (HDD), the volume is fully encrypted. For a hardware encrypted hard drive (EHDD), the volume is not perpetually unlocked.
EncryptionInProgress | The volume is partially encrypted.
DecryptionInProgress | The volume is partially encrypted.
EncryptionPaused | The volume has been paused during the encryption progress. The volume is partially encrypted.
DecryptionPaused | The volume has been paused during the decryption progress. The volume is partially encrypted.

## Ohai Version

14 (not a breaking change)

## Platform Version

Windows 10, ideally target Windows 2008 upwards (at the very least this should not fail on Windows 2008)

**Comment by kmf** [comment]
Thanks for this!

**Comment by tas50** [comment]
This will ship in Chef 14.5
