### ISSUE TITLE
Detect New EC2 Instance Class M5 (Windows)

### ISSUE THREAD

**Issue by knightorc** [chef/ohai#1234]
## Description

Similar to https://github.com/chef/ohai/issues/1082
Briefly describe the issue

## Ohai Version

Ohai 13.9.1 & 13.10.0

## Platform Version

Windows 2k12

## Ohai Output

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>ohai -v
Ohai: 13.10.0

C:\Windows\system32>ohai virtualization
{
  "systems": {

  }
}

C:\Windows\system32>ohai kernel/cs_info/manufacturer
[
  "Amazon EC2"
]

C:\Windows\system32>
```

**Comment by tas50** [comment]
The virtualization bit of this will be resolved by https://github.com/chef/ohai/pull/1317

**Comment by tas50** [comment]
C5 actually detects the ec2 portion. I just spun up a C5 instance and I get back node['ec2'] and node['cloud'] attributes

```
  "ec2": {
    "ami_id": "ami-05b83598992924b63",
    "ami_launch_index": "0",
    "ami_manifest_path": "(unknown)",
    "block_device_mapping_ami": "sda1",
    "block_device_mapping_root": "/dev/sda1",
```

The extra virtualization fields will get added by my upcoming PR, but you can upgrade to Chef 14 right now to get the actual cloud detection. It's all there.
