### ISSUE TITLE
node['ipaddress'] set to 127.0.0.1 on macOS nodes during initial run

### ISSUE THREAD

**Issue by jazaval** [chef/ohai#1237]
## Description

The initial ohai run triggered during boot by the chef-client LaunchDaemon seems to have `127.0.0.1` for the 'ipaddress' attribute. This is visible in Chef Manage as well as when `node['ipaddress']` is subsequently used in recipes. I've verified that the machines are able to reach Chef server at the time ohai ran, and therefore have actual network connectivity. 

I've observed that this seems to happen only on the first chef-client run kicked off by launchd at boot, and not at subsequent runs, so biggest impact for my use-case is that a DNS registration recipe happens at boot, meaning that 127.0.0.1 is registered to the DNS entry for the machine. I can currently work around this by guarding against that value specifically. 

## Ohai Version

Ohai: 14.2.0

## Platform Version

macOS 10.13.0 - 10.13.4

## Chef Client Output

Chef run from affected node updating DNS record template:
```
-update add mac-node.mycompany.com 3600 A 10.240.96.6
+update add mac-node.mycompany.com 3600 A 127.0.0.1
```

Subsequent run from affected node updating DNS record template:
```
-update add mac-node.mycompany.com 3600 A 127.0.0.1
+update add mac-node.mycompany.com 3600 A 10.240.96.6
```

**Comment by americanhanko** [comment]
It should be noted that the production issue was solved by decreasing the chef-client interval to occur several times within a single run (increased splay), ensuring the correct IP address was used with our implementation of the attribute.

**Comment by tas50** [comment]
Since there isn't a repro for this issue I'm going to close it out at this point. Feel free to open a new issue up if you have more details on what may have been causing the problem.
