### ISSUE TITLE
Chef 15: Write filesystem2 AIX/Solaris data to filesystem and filesystem2

### ISSUE THREAD

**Issue by tas50** [chef/ohai#1271]
We're unifying the disk data and for Chef 14.6 we introduced filesystem for AIX and Solaris. In Chef 15 we'll begin writing data to both locations but the data will be the filesystem2 data. In Chef 16 we'll nuke the filesystem2 namespace. Painful, but the least painful option.

**Comment by btm** [comment]
Looks like the plan is now to remove the `filesystem2` namespace in Chef 17: 069149c0d

**Comment by tas50** [comment]
This part is done
