### ISSUE TITLE
Amazon Linux platform_version

### ISSUE THREAD

**Issue by JCapriotti** [chef/ohai#1275]
## Description

The `platform_version` seems incorrect for Amazon Linux 1 platform. If I understand it correctly, `platform_version` should  report 1 or 2. See below for actual.

## Ohai Version

14.5.9

## Platform Version

via `/etc/system-release`:
Amazon Linux AMI release 2018.03

## Ohai Output

```
$ ohai | grep platform
[2018-10-17T22:09:39+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
  "platform": "amazon",
  "platform_version": "2018.03",
  "platform_family": "amazon",

**Comment by tas50** [comment]
Prior to the Amazon Linux 2.0 the versions are YEAR.MONTH format. Amazon used this as the version identifier from 2013 to 2018, but with the release of Amazon Linux 2 they began to refer to these releases the the 1.x release. The versions are still YEAR.MONTH and that's what Chef will return as there are no 1.X versions.
