### ISSUE TITLE
Ohai not detecting openSUSE Leap properly

### ISSUE THREAD

**Issue by megamorf** [chef/ohai#1289]
## Description

Ohai does not identify openSUSE Leap properly. I'm using the official Docker Image from https://hub.docker.com/r/opensuse/leap/
I've collected detection relevant info in this issue: https://github.com/inspec/inspec/issues/3574

I assume it fails to pass this line https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/platform.rb#L294 because its ID value is different `ID="opensuse-leap"`.

## Ohai Version

14.6.2

## Platform Version

openSUSE Leap 15

## Ohai Output

See linked issue.

**Comment by tas50** [comment]
Fixed by #1297
