### ISSUE TITLE
Backport #1299 to 14.x?

### ISSUE THREAD

**Issue by michaelklishin** [chef/ohai#1343]
Looks like https://github.com/chef/ohai/pull/1299 (and thus https://github.com/chef/ohai/pull/1299/commits/6b14655d54bef0f4f6be28f624aa1819e2393f16) is only available in Chef 15.x series. Any chance it can be backported to 14.x so that OpenSUSE Leap 15 users can, ahem, use Chef?

**Comment by michaelklishin** [comment]
Any feedback from Ohai maintainers?

**Comment by michaelklishin** [comment]
@tas50 I'm truly sorry to bother you directly but you seem to be by far most active person in the Chef project space on GitHub. No response in ~ 2 weeks in April is rough. Any opinion on this?

**Comment by tas50** [comment]
I'm uncomfortable backporting #1299 to Chef 14. It's a huge improvement to our platform detection login, but it's probably a breaking change for someone since it reworks 10 years of historical platform detection. We'd need to rework SLES 15 within the existing Chef 14 codebase.

**Comment by tas50** [comment]
I'm going to close this out at this point since #1377 has the fix for opensuse
