### ISSUE TITLE
Solaris network plugin is failing to populate under certain conditions

### ISSUE THREAD

**Issue by devoptimist** [chef/ohai#1366]
## Description

in the ohai plugin code we identify the interface line by parsing the output of `ifconfig -a` with this regex:
```if line =~ /^([0-9a-zA-Z\.\:\-]+): \S+ mtu (\d+) index (\d+)/```

However under some conditions the index number is suppressed in the ifconfig output. When the index number is missing it causes ohai to not populate any of the interface data.

The index number is suppressed when the `/etc/default/inet_type` file is present with the content
```
DEFAULT_IP=IP_VERSION4
``` 
In this situation running `ifconfig -a` (as ohai does) will result in no index number being displayed which causes our regex to not match anything. Which means no Ohai interface data populated on Solaris 11 servers with this configuration.

for more information see
https://docs.oracle.com/cd/E19253-01/816-4554/ipv6-admintasks-5/index.html
specifically `Example 8–14 Controlling Output to Select IPv4 and IPv6 Information`

## Ohai Version
Ohai: 15.0.35

## Platform Version
Sollaris 11.4

## Ohai Output
Create and populate `/etc/default/inet_type`
```
root@vagrant:~# cat << EOF >> /etc/default/inet_type
> DEFAULT_IP=IP_VERSION4
> EOF
root@vagrant:~#
```

Run ohai and see no network interfaces have been populated
```
root@vagrant:~# ohai -l debug -d /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/ohai-15.0.35/lib/ohai/plugins/solaris2/ network
{
  "interfaces": {

  }
}
[2019-05-31T18:41:23+02:00] DEBUG: Ohai took 0.16654200000000002 total seconds to run.
```
Check the output of `ifconfig -a`
```
root@vagrant:~# ifconfig -a
lo0: flags=2000000849<UP,LOOPBACK,RUNNING,MULTICAST,VIRTUAL> mtu 8232
        inet 127.0.0.1 netmask ff000000 
net0: flags=100000004843<UP,BROADCAST,RUNNING,MULTICAST,DHCP,PHYSRUNNING> mtu 1500
        inet 10.0.2.15 netmask ffffff00 broadcast 10.0.2.255
        ether 8:0:27:f7:9b:b 
```

move `/etc/default/inet_type` out of the way so it stops effecting the ifconfig output.
```
root@vagrant:~# mv /etc/default/inet_type /tmp
```

re run ifconfig -a
```
root@vagrant:~# ifconfig -a
lo0: flags=2001000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv4,VIRTUAL> mtu 8232 index 1
        inet 127.0.0.1 netmask ff000000 
net0: flags=100001004843<UP,BROADCAST,RUNNING,MULTICAST,DHCP,IPv4,PHYSRUNNING> mtu 1500 index 2
        inet 10.0.2.15 netmask ffffff00 broadcast 10.0.2.255
        ether 8:0:27:f7:9b:b 
lo0: flags=2002000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv6,VIRTUAL> mtu 8252 index 1
        inet6 ::1/128 
net0: flags=120002004841<UP,RUNNING,MULTICAST,DHCP,IPv6,PHYSRUNNING> mtu 1500 index 2
        inet6 fe80::a00:27ff:fef7:9b0b/10 
        ether 8:0:27:f7:9b:b 
```

Then run the ohai plugin again to show populated interface data
```
root@vagrant:~# ohai -l debug -d /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/ohai-15.0.35/lib/ohai/plugins/solaris2/ network

{         
  "interfaces": {             
    "lo0": {                
      "mtu": "8252",
      "index": "1",
      "flags": [
        "UP",                            
        "LOOPBACK",                     
        "RUNNING",                     
        "MULTICAST",
        "IPv6",
        "VIRTUAL"
      ],                        
      "type": "lo",          
      "number": "0",
      "encapsulation": "Loopback",                      
...
...
...
```

**Comment by tas50** [comment]
This fix has been released. Closing
