### ISSUE TITLE
RPM packages can have multiple packages with the same `name`.

### ISSUE THREAD

**Issue by jjustice6** [chef/ohai#1368]
### Describe the Enhancement:
It's legal to have two `rpm` packages with the _exact same name_ installed. not (for example) `python` and `python2.7`, but literally the exact same _name_. Unfortunately, Ohai uses the package name as the [key of the hash](https://github.com/chef/ohai/blob/v15.0.37/lib/ohai/plugins/packages.rb).

### Describe the Need:
The need here is evident from #968 , however, kernel and gpg key packages are not the only packages which have this problem. In theory, any package can have this problem as long as it is legal for the RPM packages to live side by side, such as installing libs for another architecture, or using certain vendor-provided packages.

### Current Alternative
There is no current alternative.

### Can We Help You Implement This?:
It's very evident that changing the Ohai plugin to use the full combination of name+version+release+architecture as the key would break tons of existing code. I suggested to @tas50 that we could put an 'other_versions' array in the hash, as in `node['packages'][name]['other_versions']` and put the information for every other version of the package installed in there. This may render #968 unnecessary as this would be a generic solution to the problem.

I have written custom ohai plugins with tests before, so I believe I can have a PR for you in a few days that implements this functionality.

**Comment by tas50** [comment]
Closing this out since this was merged in
