### ISSUE TITLE
Ohai shard plugin's `default_sources` always returns the fallback value

### ISSUE THREAD

**Issue by michel-slm** [chef/ohai#1378]
## Description

Ohai's shard plugin assumes `collect_os` returns a symbol, but it now returns a string. As a result it never matches any OS and returns its default value.

## Ohai Version

Found in Ohai 14.8.11 but this is still present in master as well

## Platform Version

macOS 10.14.5

## Ohai Output

N/A

**Comment by tas50** [comment]
This fix has been released. Closing this out now
