### ISSUE TITLE
Shard plugin no longer creating a seed on Amazon Linux 1

### ISSUE THREAD

**Issue by tas50** [chef/ohai#1385]
In Chef Infra Client 15.1 the Shard plugin no longer creating a seed on Amazon Linux 1

**Comment by tas50** [comment]
This is due to the lack of dmi data on the amazon linux systems. This probably happens on a good number of other RHEL platforms where dmidecode either isn't there or the path is terrible.

**Comment by jaymzh** [comment]
I will get to this when I"m back in town next week. Just acknowledging I see it. :)

**Comment by jaymzh** [comment]
OK so ... there's several solutions here.

The *best* solution is people should just install dmidecode. That's the only way to keep consistent shards to whatever people are used to.

The *next* best solution is to define `Ohai.config[:plugin][:shard_seed][:sources]` to some other set of options.

However we mightcould add some hacks here. One thing we could do is something like if `create_seed` returns empty string, then we could have a special case that goes through all sources (which includes things like `fqdn`, `hostname`, `machine_id`, and `machinename` - one of those has to work).

Another possibility is if we're amazonlinux specifically change the default, but that could break existing setups really badly if they've installed dmidecode and just upgrade Chef and bam all their machines do different things.

Thoughts?

**Comment by jaymzh** [comment]
@tas50 ^^

**Comment by tas50** [comment]
We might want to just throw a warning if dmidecode isn't found. The best solution is just to let folks install that if they need it.
