### ISSUE TITLE
Passwd plugin is still run by default in Chef15

### ISSUE THREAD

**Issue by teknofire** [chef/ohai#1393]
## Description

Because the openstack plugin depends on `etc`, the Passwd plugin will bypass the optional check that was added in #1136 and cause the passwd plugin to run without needing having to be added to `optional_plugins`.  

https://github.com/chef/ohai/blob/master/lib/ohai/plugins/openstack.rb#L27

The [check for running an optional plugin](https://github.com/chef/ohai/blob/master/lib/ohai/runner.rb#L64) happens before the dependencies have been fetched and it does not check to see if the deps are also marked as optional.

To work around this, you need to disable it by adding the following to `client.rb`

```
ohai.disabled_plugins = [:Passwd]
```

## Ohai Version

15.1.5

## Platform Version

Ubuntu 18.04
Centos 7

## Ohai Output

If relevant, please include your complete Ohai output or link to a gist. Make sure to change any values that may be sensitive.

The debug output (ohai -l debug) may be useful, but please link to a gist, or truncate it.

ZD Ticket 22931

**Comment by lamont-granquist** [comment]
All the openstack plugin is doing with etc is this:

https://github.com/chef/ohai/blob/master/lib/ohai/plugins/openstack.rb#L57

In order to check for that one user's existence, it has to walk through all of AD/LDAP/Whatever with the Passwd plugin.

That line should probably be changed to just use `Etc.getpwent` directly.

**Comment by tas50** [comment]
I'll update the openstack plugin to not use the passwd values which will fix this.

**Comment by tas50** [comment]
Fixed in 15.3.1
