### ISSUE TITLE
Update ohai to work with AWS IMDSv2

### ISSUE THREAD

**Issue by mbaitelman** [chef/ohai#1411]
## Description
AWS has announced they will be making changes to how the instance metadata endpoint works.
This *may* affect ohai.

See the announcement https://aws.amazon.com/about-aws/whats-new/2019/11/announcing-updates-amazon-ec2-instance-metadata-service/ and the user guide https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

## Platform Version
AWS EC2

**Comment by tas50** [comment]
This has been merged to master
