### ISSUE TITLE
shard_seed depends on dmidecode, which isn't available on all platforms

### ISSUE THREAD

**Issue by mattray** [chef/ohai#1465]
## Description

Running chef-client 16 on 32-bit ARM machines throws the following error message:

[2020-05-19T23:04:49+10:00] ERROR: shard_seed: Failed to get dmi property serial_number: is dmidecode installed?

Raspberry Pis and similar devices do not have dmi available to them. Despite setting 
```
override['ohai']['disabled_plugins'] = [ 'dmi' ]
```
this still throws an error at the start of the chef-client run.

Present on Debian 10, Raspbian 10, Centos 7 on Raspberry Pi 0, Raspberry Pi 3, Raspberry Pi 4, and a BeagleBone Black.

**Comment by tas50** [comment]
@jaymzh I've been running into this one on raspi boxes as well

**Comment by jaymzh** [comment]
didn't we fix this like 3 releases ago?

**Comment by jaymzh** [comment]
OK so first, we did fix this  here: https://github.com/chef/ohai/pull/1446
Second I have no idea what you expect:
```
override['ohai']['disabled_plugins'] = [ 'dmi' ]
```
to do. If you don't want to run shard_seed, disable shard seed:
```
override['ohai']['disabled_plugins'] = [ :shard_seed ]
```

If you want it to work without demidecode, then configure it using `Ohai.config[:plugin][:shard_seed][:sources]`
