### ISSUE TITLE
node['platform'] will need to be updated for macOS 10.16

### ISSUE THREAD

**Issue by chilcote** [chef/ohai#1469]
## Description
https://github.com/chef/ohai/blob/master/lib/ohai/plugins/darwin/platform.rb#L26-L30
Apple changed the output of `sw_vers -productName` from 
```
Mac OS X
```
to:
```
macOS
```

## Ohai Version

15.7.4, but it looks the same in 16.2.0.

## Platform Version

macOS 10.16 beta 1

## Ohai Output

n/a

**Comment by kmf** [comment]
According to Apple's pages it will be called `macOS 11`

**Comment by btm** [comment]
https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes
> The system ProductVersion is reported as 11.0 only on the Developer Transition Kit at this time. Existing Mac systems will temporarily report the value as 10.16.

**Comment by lamont-granquist** [comment]
this is done
