### ISSUE TITLE
Windows nodes on Azure that do not have the WAAgent are not collecting Azure attributes

### ISSUE THREAD

**Issue by jasonwbarnett** [chef/ohai#1519]
## Description

Currently Ohai uses the [WAAgent or DHCP option 245][1] as the primary means of detecting whether or not a node is in Azure. Unfortunately the detection of option 245 was [only implemented for Linux][2].

## Ohai Version

v16.4.16

## Platform Version

- Windows Server 2012R2
- Windows Server 2016

[1]: https://github.com/chef/ohai/blob/v16.4.16/lib/ohai/plugins/azure.rb#L37
[2]: https://github.com/chef/ohai/blob/v16.4.16/lib/ohai/plugins/azure.rb#L56-L68

**Comment by jasonwbarnett** [comment]
I would like to solve this issue by vendoring the [Detect Windows Azure Virtual Machine script][1]. I would like help to know if the license the software is distributed under is permissive to do such a thing.

Can someone at Chef help me out here?

[1]: https://gallery.technet.microsoft.com/scriptcenter/Detect-Windows-Azure-aed06d51

**Comment by phiggins** [comment]
That script is licensed under the "TechNet terms of use" license, and I do not see any reference to that in [license_scout](https://github.com/chef/license_scout) which is used to determine license compliance of dependencies. That means Chef legal would likely need to get involved, which means this is probably unlikely to happen unless this is determined to be a high priority.

Is this an issue you're currently running into, that you have Azure nodes that aren't being detected as such by ohai? As an alternative, from a few minutes of searching it sounds like querying this endpoint could work for determining if a node is in Azure or not: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service

**Comment by jasonwbarnett** [comment]
> Is this an issue you're currently running into, that you have Azure nodes that aren't being detected as such by ohai? As an alternative, from a few minutes of searching it sounds like querying this endpoint could work for determining if a node is in Azure or not: [docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service)

This sounds like a reasonable approach. I think I was initially swayed against doing that initially because I assumed, maybe incorrectly, that there was a specific reason that was the initial approach from day 1.

**Comment by tas50** [comment]
@phiggins We try to avoid hitting the endpoints unless we know we're on the right cloud. They all have similar IPs, but take requests different and the HTTP request timeouts are quite slow if we're not actually on an Azure system. It's possible that we have some better information available to us via WMI in Azure now. When I worked on this problem 2-3 years ago it was pretty lacking compared to AWS.

**Comment by jasonwbarnett** [comment]
Another alternative (which seems sort of crazy) is to take implement a basic DHCP client in Ruby and use that on both Linux and Windows.

**Comment by jasonwbarnett** [comment]
I just had an epiphany. We can just check to see if the DHCP domain (option 15) is set to `reddog.microsoft.com` by checking the interface configuration in the registry. I am going to whip something up and submit a PR.
