### ISSUE TITLE
zpool plugin doesn't pick up devices that begin with "xvd" or "nvme" because the regex is too restrictive

### ISSUE THREAD

**Issue by ziggythehamster** [chef/ohai#1546]
## Description

Due to [the regex on this line](https://github.com/chef/ohai/blob/master/lib/ohai/plugins/zpools.rb#L77), disks that start with `xvd` or `nvme` are not picked up. `xvd` is how disks are typically mapped with block device mapping on AWS, and `nvme` is what those symlink to as well as what the NVMe instance store volumes would come up as.

An example `xvd`: `xvdcz`
An example `nvme`: `nvme2n1`

## Ohai Version

15.12.0, but this is in master and would clearly fail in all versions

## Platform Version

CentOS Linux release 8.2.2004 (Core)

## Ohai Output

Notice that `devices` is empty:

```json
  "zpools": {
    "syspool": {
      "pool_size": "19.5G",
      "pool_allocated": "954M",
      "pool_free": "18.6G",
      "capacity_used": "4%",
      "dedup_factor": "1.00x",
      "health": "ONLINE",
      "zpool_version": null,
      "devices": {

      }
    }
  }
```

**Comment by tas50** [comment]
We probably need a better way overall of detecting the drives in the pools. Here's the output of my zpool:

```
  pool: storage
 state: ONLINE
  scan: scrub repaired 0B in 0 days 08:36:39 with 0 errors on Sun Oct 11 09:00:42 2020
config:

	NAME                                          STATE     READ WRITE CKSUM
	storage                                       ONLINE       0     0     0
	  raidz2-0                                    ONLINE       0     0     0
	    ata-WDC_WD60EZAZ-00SF3B0_WD-WX32D203UXYK  ONLINE       0     0     0
	    ata-WDC_WD60EZAZ-00SF3B0_WD-WX52D30A4P3Z  ONLINE       0     0     0
	    ata-WDC_WD60EZAZ-00ZGHB0_WD-WX82D5044LV0  ONLINE       0     0     0
	    ata-WDC_WD60EZRZ-00RWYB1_WD-WX21DB50936A  ONLINE       0     0     0

errors: No known data errors
```

None of those drives would get picked up either

**Comment by tas50** [comment]
My output is fixed by this PR: https://github.com/chef/ohai/pull/1547

**Comment by ziggythehamster** [comment]
Here's mine:

```
  pool: syspool
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        syspool     ONLINE       0     0     0
          xvdcz     ONLINE       0     0     0

errors: No known data errors
```

Some people use /dev/disk/by-path entries, which would have even less parseable output. Maybe the solution is to run `zpool status -g` so all devices have the same format of name:

```
  pool: syspool
 state: ONLINE
  scan: none requested
config:

        NAME                   STATE     READ WRITE CKSUM
        syspool                ONLINE       0     0     0
          4418022860032193234  ONLINE       0     0     0

errors: No known data errors
```

But then you have to parse the `zdb` output to look that back up again, so probably figuring out some better parsing strategy would be better.

**Comment by ziggythehamster** [comment]
I would not be:

```
# zpool status syspool -L
  pool: syspool
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        syspool     ONLINE       0     0     0
          nvme2n1   ONLINE       0     0     0

errors: No known data errors
```

**Comment by tas50** [comment]
@ziggythehamster Any chance you're on the Chef Community Slack? If so hit me up at tas50

**Comment by ziggythehamster** [comment]
I am not, but I guess I could join

**Comment by tas50** [comment]
This will ship in the next release of Ohai. Thanks for the heads up @ziggythehamster
