### ISSUE TITLE
hostnamectl plugin eats values with colons in them

### ISSUE THREAD

**Issue by ziggythehamster** [chef/ohai#1559]
## Description

Given the following hostnamectl output:

```
   Static hostname: xxxxxxx
Transient hostname: xxxxx
         Icon name: computer-vm
           Chassis: vm
        Deployment: staging
          Location: AWS us-west-1b xxxxx
        Machine ID: xxx
           Boot ID: xxx
    Virtualization: kvm
  Operating System: CentOS Linux 8 (Core)
       CPE OS Name: cpe:/o:centos:centos:8
            Kernel: Linux 5.9.6-1.el8.elrepo.x86_64
      Architecture: x86-64
```

The "CPE OS Name" field is parsed by ohai like this:

```
  "cpe_os_name": "cpe",
```

This is because on [line 29](https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/hostnamectl.rb#L29), it goes `key, val = line.split(":")` instead of `key, val = line.split(':', 2)`:

```
irb(main):001:0> line = "       CPE OS Name: cpe:/o:centos:centos:8"
=> "       CPE OS Name: cpe:/o:centos:centos:8"
irb(main):002:0> line.split(':', 2)
=> ["       CPE OS Name", " cpe:/o:centos:centos:8"]
```

## Ohai Version

15.12.0, but the bug is in master

## Platform Version

CentOS 8

## Ohai Output

See above

**Comment by tas50** [comment]
Fixed by https://github.com/chef/ohai/pull/1560
