### ISSUE TITLE
Properly report CPU data on M1 chips

### ISSUE THREAD

**Issue by tas50** [chef/ohai#1589]
Right now Ohai is reporting the Rosetta2 CPU which is a fake Intel chip. We need to make sure we properly report the M1 chip here.

**Comment by lucasjhall** [comment]
@tas50 same for `node['hardware']` as seen [here](https://github.com/chef/ohai/blob/7557513c626fb4f2372a09074e1411b5fc8de64f/lib/ohai/plugins/darwin/hardware.rb#L40)
```
 hw_hash = system_profiler("SPHardwareDataType")
```

At the root is infra's lack of support for the arm64/universal arch- even performing such tasks via shell_out will still return a rosetta translated output unless `arch` is used to designate `arm64` execution:

```ruby
chef (16.7.61)> shell_out('system_profiler SPHardwareDataType').stdout
 => "Hardware:\n\n    Hardware Overview:\n\n      Model Name: MacBook Pro\n      Model Identifier: MacBookPro17,1\n      Processor Name: Unknown\n      Processor Speed: 2.4 GHz\n..." 
```

```ruby
chef (16.7.61)> shell_out('/usr/bin/arch -arm64 system_profiler SPHardwareDataType').stdout
 => "Hardware:\n\n    Hardware Overview:\n\n      Model Name: MacBook Pro\n      Model Identifier: MacBookPro17,1\n      Chip: Apple M1\n      Total Number of Cores: 8 (4 performance and 4 efficiency)\n..."
```

**Comment by btm** [comment]
@lucasjhall do you have a full ohai output on an M1 that you could post to a gist?

**Comment by btm** [comment]
@marcparadise when you have a native build of Infra Client on the DTK, it would be useful to make a 3 part gist with:

1. ohai output on the DTK from the emulated build
2. ohai output on the DTK from the native build
3. a diff of some kind

**Comment by tas50** [comment]
Closing this out since we're going the native M1 build route. There's no need to hack a x86 build to show the proper data.
