### ISSUE TITLE
instance types (c5.2xlarge, c5.4xlarge, m5.2xlarge, m5.4xlarge, m5a.4xlarge) using CFT it fails with this error

### ISSUE THREAD

**Issue by vanumalla** [chef/ohai#1601]
# Describe the problem
Fails with this Error when trying to build the above instance types, it works with m5.xlarge though. Not sure if ohai does not support the former?
  NoMethodError
  -------------
  undefined method `[]' for nil:NilClass

## Software Version
System Info:
  ------------
  chef_version=12.19.36
  platform=amazon
  platform_version=2
  ruby=ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
  program_name=/bin/chef-client
  executable=/opt/chef/bin/chef-client

## Replication Case
Bring up any amazonLinux or RHEL with a common linux cookbook it fails with this error because it fails with a null tag returned

## Stacktrace
Generated at 2021-01-27 10:30:39 -0500
NoMethodError: undefined method `[]' for nil:NilClass
/var/chef/cache/cookbooks/uw-octopus-client-linux/recipes/rhel7.rb:2:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/run_context.rb:338:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/run_context.rb:294:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/run_context.rb:293:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/run_context.rb:293:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/uw-octopus-client-linux/recipes/default.rb:13:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/run_context.rb:338:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/run_context.rb:294:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/run_context.rb:293:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/run_context.rb:293:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/uw-apcapi/recipes/default.rb:16:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/run_context.rb:338:in `load_recipe'

**Comment by tas50** [comment]
@vanumalla Chef 12 has been EOL for several years. You'll want to upgrade to the latest Chef Infra Client 16, which includes a large number of Ohai improvements.

**Comment by vanumalla** [comment]
Hello tas50, I did upgrade Chef client to 16 but is still failing. Thank you for the quick response

**Comment by tas50** [comment]
What's in this cookbook actually? Are you sure this is something missing in Ohai or is this recipe just not working correctly with amazon linux?

**Comment by vanumalla** [comment]
Hey Tim, nothing wrong with ohai, its the recipe itself not working
correctly. Thank you,

**Comment by tas50** [comment]
Good to know. I'll close this out then.
