### ISSUE TITLE
Rework Linux virtualization plugin to use systemd-detect-virt

### ISSUE THREAD

**Issue by tas50** [chef/ohai#1619]
Where we can this gives us a very simple way to check the guest. It will probably expand our detection a good amount and gives us a nice container detection.

https://www.freedesktop.org/software/systemd/man/systemd-detect-virt.html

**Comment by ramereth** [comment]
FWIW my enhancements in #1454 also pull in some fixes for virt detection using `lscpu`. I'm not sure if `systemd-detect-virt` also uses that or uses it's own magic.

**Comment by tas50** [comment]
I'm actually going to close this one out now. I dug into systemd-detect-virt and it has a ton of issues. It's better than ohai in some ways and in others it's just a total tire fire.
