### ISSUE TITLE
IP address is not detected

### ISSUE THREAD

**Issue by whyte624** [chef/ohai#1655]
## Description

[2021-04-19T12:35:32+00:00] WARN: Plugin Network: unable to detect ipaddress

The windows is installed on Azure VM.
Moreover all system related attributes are empty:

```
"kernel": {

},
"memory": {
  "swap": {

  }
},
"network": {
  "interfaces": {

  }
},
"counters": {
  "network": {

  }
},
"os": "windows",
"os_version": null,
"platform": "windows",
"platform_version": null,
"platform_family": "windows",
"dmi": {

},
"virtualization": {
  "systems": {

  }
},
```

However, Azure mixin returns all parameters.

## Ohai Version
15.16.4
16.4.41
16.13.0

## Platform Version

Windows Server 2016

## Ohai Output

[2021-04-19T12:35:32+00:00] WARN: Plugin Network: unable to detect ipaddress

**Comment by whyte624** [comment]
Data was not collected due to failure in WMI service in Azure.

Problem was fixed after WMI repository has been rebuilt.

More info here: https://community.spiceworks.com/how_to/21413-rebuilding-the-wmi-repository.

**Comment by tas50** [comment]
Thanks for the followup @whyte624
