### ISSUE TITLE
Filesystem bug for some and a feature for others

### ISSUE THREAD

**Issue by jasonwbarnett** [chef/ohai#1703]
## Description

The [pattern in the filesystem plugin](https://github.com/chef/ohai/blob/main/lib/ohai/plugins/filesystem.rb#L397-L404) is a little confusing. I understand that people want an easy way to access the data they're after, but duplicating the data in order to achieve this goal seems like a design smell.

Why was the duplicate data approach taken over some sort of helper method to access and find filesystem information by mount/device/etc? i.e.

```ruby
node.filesystem_by_mount('/my/mount')

node.filesystem_by_device('/dev/sda1')
```

So I guess this is sort of a question and a design proposal.

I'm guessing that shoving objects into those namespaces would be a big no no, so I am not even going to suggest that, but could be cool and achieve the same thing. imagine with me for just a moment... 🎭 :

```ruby
module Ohai
  class FilesystemPresenter
    def [](accessor)
      case accessor
      when "by_device"
        #=> return device "view"
      when "by_mountpoint"
        #=> return mountpoint "view"
      when "by_pair"
        #=> return pair "view"
      else
        nil
      end
    end

    # For Automate
    def to_json
      #=> return standard "view"
    end
  end
end

fs = Ohai::FilesystemPresenter.new

node.automatic["filesystem"] = fs
```

Not sure what you would do for the reporting into Automate, etc. but I assume you could present a view that would only contain a single copy of the data that is an agreed *standard* "view".

**Comment by NaomiReeves** [comment]
There's some context in the original PR: #559 but cc @jaymzh who is the original author.

**Comment by jaymzh** [comment]
That would be a whole new pattern for Ohai that doesn't exist today. It would also be challenging for non-chef users of Ohai to use it. If such a structure existed, we could have used it, but it didn't and doesn't. The way people interface with Ohai is simply via JSON, or the node attributes.

In addition, we really wanted a back-compat way for people to access data in the old, non-safe data to simplify a migration that was already pretty challenging (switch to fs2, then back to fs1), so allowing them to just do `by_device` for people who didn't need the safer data kept their code nearly identical. Or at least let them make that other change (which requires more thought/planning) at a later time.

So, yup, in the abstract, absolutely - if we were building Ohai from scratch something like that would be super cool. Or maybe in a major version bump to start building something like that in, not specific to filesystem, but as a way to add helpers to plugins. I think we'd be pretty open to a discussion around that. But as Ohai stands, the current implementation was, IMO, the right call, and I would not call it a bug at all.

So if you're interested in starting a discussion on this as a feature for the next major version of Ohai, and you're willing to do the work to implement it (and probably dig through all the other plugins that could use helpers, like `network`, and see how to try to make this as generic as possible), and still work for non-chef Ohai users, then we should probably do that as a very different issue.

For now, I'm going to close this, but you're welcome to re-open it if you have further questions.
