### ISSUE TITLE
Ohai should use lsblk instead of (or in addition to) blkid

### ISSUE THREAD

**Issue by jaymzh** [chef/ohai#351]
Ohai discovers filesystems with blkid specifically to discover umounted filesystems, but blkid is quite bad at discovering these.

For example, note what blkid finds:

```
# blkid
/dev/sda1: LABEL="/boot" UUID="b132cf93-1c39-4a21-ad4f-13990df55a2e" TYPE="ext3" 
/dev/sda2: UUID="e8da514e-d510-4925-afc6-a8fecda858e1" TYPE="swap" 
/dev/sda3: LABEL="/" UUID="62744bd7-434f-41a1-b9e7-21657a4a0cf9" TYPE="ext4"
```

Now note what lsblk finds:

```
# lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda       8:0    0   1.8T  0 disk 
├─sda1    8:1    0   256M  0 part /boot
├─sda2    8:2    0     2G  0 part 
└─sda3    8:3    0   1.8T  0 part /
fioa    252:0    0 670.6G  0 disk 
└─fioa1 252:1    0 670.6G  0 part 
fiob    252:16   0 670.6G  0 disk 
└─fiob1 252:17   0 670.6G  0 part 
```

Note that blkid CAN tell you things about the extra device:

```
# blkid /dev/fioa
/dev/fioa: LABEL="/mnt/fio0" UUID="f104098d-ccab-474a-b884-2c60be546a71" TYPE="xfs" 
# blkid /dev/fiob
/dev/fiob: LABEL="/mnt/fio1" UUID="6e2d80fb-bd9e-4b95-a2a4-96b60a11a5d6" TYPE="xfs" 
```

Something like this would be more useful to Ohai:

```
# lsblk -n -o name,fstype,mountpoint,label,uuid -r
sda    
sda1 ext3 /boot /boot b132cf93-1c39-4a21-ad4f-13990df55a2e
sda2 swap   e8da514e-d510-4925-afc6-a8fecda858e1
sda3 ext4 / / 62744bd7-434f-41a1-b9e7-21657a4a0cf9
fioa xfs  /mnt/fio0 f104098d-ccab-474a-b884-2c60be546a71 fioa1    
fiob xfs  /mnt/fio1 6e2d80fb-bd9e-4b95-a2a4-96b60a11a5d6 fiob1    
```

Now, in case you're interested WHY this crap happens, there are several reasons:

1. blkid uses libblkid which does discovery by walking /proc/partitions and then using a horrible heuristic decides which ones are worth reporting on. See fun bugs like this one:
http://marc.info/?l=linux-ext4&m=119636478426226&w=2

2. lsblk walks /sys/block and reports on everything, period. It uses libblkid only to actually get data from the devices once it has the list.

I've verified that lsblk exists in CentOS6 and later, Debian, Ubuntu. However, CentOS5 and some more esoteric Linuxes don't have lsblk, so a fallback to blkid is probably useful.

I'll have pull-requests for you shortly.

**Comment by lamont-granquist** [comment]
think this is done, closing.
