### ISSUE TITLE
ohai detects wrong ipv6 address

### ISSUE THREAD

**Issue by damacus** [chef/ohai#380]
I'm not sure if I've missed something in diagnosing this one so bear with me. 

We've disabled ipv6 on the our redhat 5.10 machines and I think as a result ohai is still detecting a IPv6 address, the address reported is an IPv4 addr. 

We're using chef-client 11.12.8

**Comment by randyrue** [comment]
Having the same problem on CentOS 6.6/Chef 12.1.1/Ohai 8.1.1, in this case I can't use the snmp cookbook because it insists on configuring an ip6 source. Any suggestions?

**Comment by thommay** [comment]
@randyrue, @damacus, @rarenerd  can you show us what the output of `ip addr` is please, and also `ohai network`.

**Comment by randyrue** [comment]
[root@rooo ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
     inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast 
state UP qlen 1000
     link/ether 00:50:56:9c:2d:7b brd ff:ff:ff:ff:ff:ff
     inet 140.107.88.66/23 brd 140.107.89.255 scope global eth0
[root@rooo ~]# ohai network
{
   "interfaces": {
     "lo": {
       "mtu": "65536",
       "flags": [
         "LOOPBACK",
         "UP",
         "LOWER_UP"
       ],
       "encapsulation": "Loopback",
       "addresses": {
         "127.0.0.1": {
           "family": "inet",
           "prefixlen": "8",
           "netmask": "255.0.0.0",
           "scope": "Node"
         }
       },
       "state": "unknown"
     },
     "eth0": {
       "type": "eth",
       "number": "0",
       "mtu": "1500",
       "flags": [
         "BROADCAST",
         "MULTICAST",
         "UP",
         "LOWER_UP"
       ],
       "encapsulation": "Ethernet",
       "addresses": {
         "00:50:56:9C:2D:7B": {
           "family": "lladdr"
         },
         "140.107.88.66": {
           "family": "inet",
           "prefixlen": "23",
           "netmask": "255.255.254.0",
           "broadcast": "140.107.89.255",
           "scope": "Global"
         }
       },
       "state": "up",
       "arp": {
         "140.107.89.11": "00:50:56:9c:67:32",
         "140.107.88.1": "00:00:0c:07:ac:2a",
         "140.107.88.132": "00:50:56:9c:33:c0"
       },
       "routes": [
         {
           "destination": "140.107.88.0/23",
           "family": "inet",
           "scope": "link",
           "proto": "kernel",
           "src": "140.107.88.66"
         },
         {
           "destination": "169.254.0.0/16",
           "family": "inet",
           "scope": "link",
           "metric": "1002"
         },
         {
           "destination": "default",
           "family": "inet",
           "via": "140.107.88.1"
         },
         {
           "destination": "140.107.88.0/23",
           "family": "inet6",
           "scope": "link",
           "proto": "kernel",
           "src": "140.107.88.66"
         },
         {
           "destination": "169.254.0.0/16",
           "family": "inet6",
           "scope": "link",
           "metric": "1002"
         },
         {
           "destination": "default",
           "family": "inet6",
           "via": "140.107.88.1"
         }
       ]
     }
   },
   "default_interface": "eth0",
   "default_gateway": "140.107.88.1",
   "default_inet6_interface": "eth0",
   "default_inet6_gateway": "140.107.88.1"
}
[root@rooo ~]#

**Comment by rarenerd** [comment]
Tested in a Virtualbox with the opscode-centos-6.6 image:
```
[root@localhost ~]# ohai --version
Ohai: 8.2.0
[root@localhost ~]# cat /etc/redhat-release
CentOS release 6.6 (Final)
```

```
[root@localhost ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:70:c7:f1 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
```

```
[root@localhost ~]# ohai network
{
  "interfaces": {
    "lo": {
      "mtu": "65536",
      "flags": [
        "LOOPBACK",
        "UP",
        "LOWER_UP"
      ],
      "encapsulation": "Loopback",
      "addresses": {
        "127.0.0.1": {
          "family": "inet",
          "prefixlen": "8",
          "netmask": "255.0.0.0",
          "scope": "Node"
        }
      },
      "state": "unknown"
    },
    "eth0": {
      "type": "eth",
      "number": "0",
      "mtu": "1500",
      "flags": [
        "BROADCAST",
        "MULTICAST",
        "UP",
        "LOWER_UP"
      ],
      "encapsulation": "Ethernet",
      "addresses": {
        "08:00:27:70:C7:F1": {
          "family": "lladdr"
        },
        "10.0.2.15": {
          "family": "inet",
          "prefixlen": "24",
          "netmask": "255.255.255.0",
          "broadcast": "10.0.2.255",
          "scope": "Global"
        }
      },
      "state": "up",
      "arp": {
        "10.0.2.2": "52:54:00:12:35:02",
        "10.0.2.3": "52:54:00:12:35:03"
      },
      "routes": [
        {
          "destination": "10.0.2.0/24",
          "family": "inet",
          "scope": "link",
          "proto": "kernel",
          "src": "10.0.2.15"
        },
        {
          "destination": "169.254.0.0/16",
          "family": "inet",
          "scope": "link",
          "metric": "1002"
        },
        {
          "destination": "default",
          "family": "inet",
          "via": "10.0.2.2"
        },
        {
          "destination": "10.0.2.0/24",
          "family": "inet6",
          "scope": "link",
          "proto": "kernel",
          "src": "10.0.2.15"
        },
        {
          "destination": "169.254.0.0/16",
          "family": "inet6",
          "scope": "link",
          "metric": "1002"
        },
        {
          "destination": "default",
          "family": "inet6",
          "via": "10.0.2.2"
        }
      ]
    }
  },
  "default_interface": "eth0",
  "default_gateway": "10.0.2.2",
  "default_inet6_interface": "eth0",
  "default_inet6_gateway": "10.0.2.2"
}
```
