### ISSUE TITLE
Platform version is missing on archlinux platform

### ISSUE THREAD

**Issue by kamaradclimber** [chef/ohai#405]
When running ohai, on archlinux, platform_version is not filled.

This comes from archlinux having no "version" per se since it is a rolling release distro.
https://github.com/opscode/ohai/blob/7-stable/lib/ohai/plugins/linux/platform.rb#L84 makes it clear.

Hovewer, the comment on https://github.com/opscode/ohai/blob/7-stable/lib/ohai/plugins/linux/platform.rb#L85 suggests we could use the kernel version instead.

(ps: having no platform version makes chef test crash)

**Comment by btm** [comment]
#473 has been merged. barring any testing issues this should make it into a release shortly.
