### ISSUE TITLE
ohai ipaddress returns loopback address on servers virtualized through OpenVZ

### ISSUE THREAD

**Issue by dragolabs** [chef/ohai#415]
So what about OHAI-237 feature? In short: in openvz guest system ohai detect ip 127.0.0.2. not real.
More info and patch available in JIRA thread: https://tickets.opscode.com/browse/OHAI-237?focusedCommentId=49337&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-49337

**Comment by lamont-granquist** [comment]
If someone wants to extract the patch from jira and submit a PR that would be useful.

**Comment by jaymzh** [comment]
I really wish there was a more generic solution. On systems with tunl0 or iptnl0 it catches those too. If you don't have a default route it completely throws the logic as well. Meh.
