### ISSUE TITLE
make hint system more user-friendly

### ISSUE THREAD

**Issue by juliandunn** [chef/ohai#422]
The mechanism by which users pass in hints to Ohai is not the most user-friendly (JSON blobs that are either empty or with mysterious contents). Could we consider refactoring it to just be a configuration flag?

**Comment by tas50** [comment]
Previously we needed hints for just about every cloud plugin as we lacked ways to properly detect the providers. For the last 8+ months we've had solid auto detection on all clouds except Azure which lacks a metadata endpoint. Rackspace, GCE, EC2, Openstack all auto detect and grab metadata. Ideally people just stop using the hints. If Azure gets a metadata endpoint we can move to a world where the hints are an optional fallback when things don't work as they should.

**Comment by tas50** [comment]
I'm going to close this out at this point. We've eliminated the main reason for using the hints and I don't see the return being worth the effort of refactoring at this point.
