### ISSUE TITLE
Invalid pid, name used after sigar fails to throw exception

### ISSUE THREAD

**Issue by werkt** [chef/ohai#423]
Filed a bug with sigar (https://github.com/hyperic/sigar/issues/48), but observed this through chef/ohai, so it is susceptible to it now and can be worked around.

The rescue call in lib/ohai/plugins/network_listeners.rb is insufficient to prevent invalid pids from being used.  After sigar throws an exception for a single 0 pid (its invalid pid return) call to proc_state, all subsequent proc_state calls within the same sigar context do not throw.  This can be worked around until they correct this behavior by throwing on pid == 0:

```ruby
begin
  pid = sigar.proc_port(conn.type, port)
  throw ArgumentError.new("No such process") if pid == 0
  listeners[port][:pid] = pid
  listeners[port][:name] = sigar.proc_state(pid).name
rescue
end
```

**Comment by smurawski** [comment]
This is definitely a valid bug, but likely won't make our backlog since it is a edge case.  We'd be happy to take a patch or PR to resolve this issue.

If you think that this is a more pervasive issue, I'd love to hear the impact and that may change our evaluation of the issue.

**Comment by werkt** [comment]
This caused roughly 1 in 20 chef-client runs to fail, segfaulting ruby.  With the workaround in place, we have not experienced a bad exit status for chef-client in 4 months (running at least 2/day).

**Comment by lamont-granquist** [comment]
we'll need a PR to get this merged
