### ISSUE TITLE
openstack kvm guest not detected by virtualization plugin

### ISSUE THREAD

**Issue by bkw** [chef/ohai#425]
On a vm running on an openstack compute node using kvm: 

```shell
root@default-ubuntu-1404:~# ohai virtualization
{
  "systems": {
    "kvm": "host"
  },
  "system": "kvm",
  "role": "host"
}
````

The virtualization plugin somewhat arbitrarily assumes that when kvm modules are present we must be a host. In my case the machine does have the modules loaded, but really is a guest:

```shell
root@default-ubuntu-1404:~# cat /proc/modules | grep kvm
kvm_intel 143060 0 - Live 0xffffffffa0114000
kvm 451511 1 kvm_intel, Live 0xffffffffa0082000
````

Openstack seems to be detectable reliably by dmidecode:
```shell
root@default-ubuntu-1404:~# dmidecode -s system-product-name
OpenStack Nova
```

I'd supply a pull request, but I don't know what to put into the `system` key. Would the following be acceptable?

```json
{
  "systems" : {
    "openstack nova": "guest"
  },
  "system" : "openstack nova",
  "role" : "guest"
}
```

**Comment by lamont-granquist** [comment]
Did #463 fix this?

**Comment by lamont-granquist** [comment]
I'm going to close this, if #463 didn't fix it, please re-open
