### ISSUE TITLE
"ohai -d" doesn't work in windows

### ISSUE THREAD

**Issue by docwhat** [chef/ohai#435]
`ohai -d c:\chef\ohai_plugins` doesn't seem to work in Windows.  Nothing I could do would make it work.

Even worse, when I tried `cd c:\chef\ohai_plugins ; ohai -d .` It generated errors like it was trying to load the ohai/lib directory as plugins! (woops!)

I think something is wrong with the code that accepts that directory path and it isn't expanding it at program start.

**Comment by drag00n** [comment]
I just tried this myself and it seems to work now. I'm using chef-client v12.0.3

**Comment by lamont-granquist** [comment]
closing since this appears to be fixed.
