### ISSUE TITLE
Zend Engine and Zend OPcache versions should be exposed in PHP plugin

### ISSUE THREAD

**Issue by tas50** [chef/ohai#440]
I'd like to add the Zend Engine version and Zend Opcache version to the PHP plugin.  This data is really important for determining how you should template out the php.ini file and would be really helpful for anyone doing wordpress.  Before I go and toss something together I'm curious what Chef folks think the best way to handle the output would be.

Here's the current output:
    "php": {
      "version": "5.5.14",
      "builddate": "Sep  9 2014 19:09:25"
    },

Zend Engine version string will be in every version of PHP, but OPcache is optional so a big part of exposing this data is allowing people to see if the key exists.  Would something like this make sense?

    "php": {
      "version": "5.5.14",
      "builddate": "Sep  9 2014 19:09:25",
      "zend_engine_version": "v2.5.0",
      "zend_opcache_version": "v7.0.3"
    },

If opcache isn't present the key could be either nil or not present altogether.

**Comment by tfitch** [comment]
Closing issue as PR #441 has now been merged.  Thanks @tas50!
