### ISSUE TITLE
plugins/linux/virtualization: lxc contains a check for a binary that does not exist upstream

### ISSUE THREAD

**Issue by cburroughs** [chef/ohai#488]
https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/virtualization.rb#L26

There is no `lxc-version` binary part of the stable/LTS 1.0.x series of lxc releases.  It may have existed as part of older (0.8.0) releases.

**Comment by btm** [comment]
Looking at [LP #1273689](https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1273689), it looks like ```lxc-start --version``` is a good alternative for 1.0.0, but notably didn't exist previously so you have to try both.

**Comment by tas50** [comment]
Closing this out since it looks like we fixed in Oct.
