### ISSUE TITLE
DigitalOcean Metadata support

### ISSUE THREAD

**Issue by rmoriz** [chef/ohai#492]
(Feature request)
DigitalOcean now provides a metadata service over http, similar to AWS:
https://developers.digitalocean.com/documentation/metadata/

Would be nice to have such information with ohai (and chef).

**Comment by mitayai** [comment]
how about

```@@ -15,6 +15,7 @@
# limitations under the License.

require 'ohai/util/ip_helper'
require 'json'

Ohai.plugin(:DigitalOcean) do
  include Ohai::Util::IpHelper
@@ -62,6 +63,10 @@ Ohai.plugin(:DigitalOcean) do
    hint?('digital_ocean') || File.exist?(DIGITALOCEAN_FILE)
  end

  def extract_digitalocean_metadata
    JSON.parse(Net::HTTP.get(URI.parse('http://169.254.169.254/metadata/v1.json')))
  end

  collect_data do
    if looks_like_digital_ocean?
      digital_ocean Mash.new
@@ -73,9 +78,10 @@ Ohai.plugin(:DigitalOcean) do
      # Digital Ocean's v2 API structures things:
      # https://developers.digitalocean.com/#droplets
      digital_ocean[:networks] = extract_droplet_ip_addresses
      digital_ocean[:metadata] = extract_digitalocean_metadata
    else
      Ohai::Log.debug("No hints present for digital_ocean.")
      false
    end
  end
end
end 
```

**Comment by rmoriz** [comment]
can you just post a diff of the current ip-address-only code?

**Comment by rmoriz** [comment]
well… you're missing all the iteration over the metadata endpoints, like it's done in ec2 https://github.com/chef/ohai/blob/master/lib/ohai/mixin/ec2_metadata.rb

Unfortunately I don't have a sponsor to contribute a patch at this time.

**Comment by bdwyertech** [comment]
This probably needs to be done sooner rather than later, cloud and cloud_v2 are currently broken on new droplets!

http://bdwyertech.net/2015/10/30/digitalocean-chef-and-ohai-retrieving-a-droplets-private-ip-address/

**Comment by thommay** [comment]
@mitayai can you submit this as a pull request?

**Comment by mitayai** [comment]
@thommay i don't have permissions to do that :-(

**Comment by bdwyertech** [comment]
Quite surprised how quiet this is being that `cloud_v2` is picking up the wrong IP address for `local_ipv4`...

**Comment by thommay** [comment]
this is implemented in #649

**Comment by GenPage** [comment]
@thommay @bdwyertech @rmoriz I'm taking over for @mitayai on this. I'll submit a new PR when it's ready.

**Comment by GenPage** [comment]
I have submitting a new PR for this #773

**Comment by rmoriz** [comment]
by the way: DigitalOcean retired the hints file `/etc/digitalocean`, it will not be created on new VMs e.g. Debian 8-based VMs. So this is currently already broken. Please merge #773 

DigitalOcean Support:


> As for your question, from my understanding this hint file has not been implemented into any of our images for Debian 8.x, as we are trying to keep minimalistic images that match base installs as close as possible. I will be sure to reach out to our images team for confirmation and more information on this, but as a workaround there are some other ways to detect a Digitalocean droplet. 
> 
> To start, one great way is to check the Cloud Init service config file, as this is specifically set to use "DigitalOcean" as the provider, which is a way to see if a server is on our platform. This can be found at /etc/cloud/cloud.cfg, and in this you can see that DigitalOcean is set as the "datasource_list" option. 
> 
> ...
> 
> Thanks for waiting! I got some confirmation from our Images team, and it sounds like this was a desired as this hint file was "non standard". As for detecting if a system is a DigitalOcean droplet, you can use the method I shared earlier with /etc/cloud/cloud.cfg, or you can also use the following command: 
> $dmidecode -s system-manufacturer 
> DigitalOcean 
> 
> Note that this command will only work on droplets made after April, but this should be a valid method to use for any new created droplets. :) 
>

**Comment by GenPage** [comment]
Note, that my PR has been expanded on in https://github.com/chef/ohai/pull/823

**Comment by tas50** [comment]
Closing this as we have the PR and are scheduling it for merge with Chef / Ohai 13
