### ISSUE TITLE
Intermittent Build Failures - Travis CI

### ISSUE THREAD

**Issue by smurawski** [chef/ohai#496]
Several pull requests have intermittent build failures attempting to output the results of Ohai.

There doesn't appear to be any difference in the PRs that build successfully and PRs that fail. 

The error message is:
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:50:in `raise_error_for_status': Invalid UTF-8 string: cannot encode to UTF-8 (FFI_Yajl::EncodeError)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `do_yajl_encode'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `encode'
	from /home/travis/build/chef/ohai/lib/ohai/system.rb:181:in `json_pretty_print'
	from /home/travis/build/chef/ohai/lib/ohai/application.rb:97:in `run_application'
	from /home/travis/build/chef/ohai/lib/ohai/application.rb:70:in `run'
	from /home/travis/build/chef/ohai/bin/ohai:42:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ohai:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ohai:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
The command "bundle exec ohai" exited with 1.

**Comment by cmluciano** [comment]
For an example you can look here at #495 where both commits triggered the error

**Comment by cmluciano** [comment]
@smurawski I think this can be closed now. The problem IIRC was due to ffi-yajl problems.
