### ISSUE TITLE
Ohai Should Be Able To Handle Binary UserData from ec2 Plugin

### ISSUE THREAD

**Issue by sean-horn** [chef/ohai#503]
Zendesk 3391

As customers, I, Amazon, and Atlassian would like to send binary userdata to EC2 instances.
This is implicitly allowed by AWS and the [cloud-init package] [1] and so Chef should allow it too.

When the current Ohai 8.1.1 tries to display any binary userdata at the end of its standalone run or during the node.save at the end of chef-client runs, it becomes sad, with 

    /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:50:in `raise_error_for_status': Invalid UTF-8 string: cannot encode to UTF-8 (FFI_Yajl::EncodeError) 
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl' 
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl' 
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl' 
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `do_yajl_encode' 
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `encode' 
    from /opt/chef/embedded/apps/ohai/lib/ohai/system.rb:181:in `json_pretty_print' 
    from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:97:in `run_application' 
    from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:70:in `run' 
    from /opt/chef/embedded/apps/ohai/bin/ohai:42:in `<top (required)>' 
    from /usr/bin/ohai:23:in `load' 
    from /usr/bin/ohai:23:in `<main>'

This PR might help https://github.com/chef/ohai/pull/504

[1]: http://cloudinit.readthedocs.org/en/latest/topics/format.html

**Comment by apsoto** [comment]
Previously working chef run's on EC2 will suddenly start failing once binary data is passed to new instances, as we are experiencing.

In our case, the chef bootstrapped Elastic Build nodes for our CI/CD infrastructure on Bamboo OnDemand broke with a recent release of Bamboo OnDemand.  Bamboo changed the way it launches EC2 instances by compressing the userdata attribute to fit more data.

**Comment by apsoto** [comment]
FYI - this issue was reported two years ago as well

https://tickets.opscode.com/browse/OHAI-516

**Comment by apsoto** [comment]
This bug causes Chef to fail on EC2 nodes that pass binary data via userdata.  At the moment, any EC2 node I have to first launch, then ssh in, manually edit the ohai source on the box, and finally re-run chef-client.

What can we do to move this along?  Is there a way to use a forked/patched ohai ?

**Comment by lamont-granquist** [comment]
fixed by #548 and or chef/chef#3320
