### ISSUE TITLE
Feature: Add a gigabit flag to interfaces that have been configured for 1Gbps+ network speeds

### ISSUE THREAD

**Issue by evaryont** [chef/ohai#507]
I have a variety of devices, a few that have both megabit interfaces (10/100) and others that have gigabit speed interfaces (10/100/1000). Ohai doesn't seem to tell me if a given device is indeed configured as gigabit.

`ip addr` shows this:

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:51:e4:40 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe51:e440/64 scope link
       valid_lft forever preferred_lft forever
```

And the output includes '1000' for eth0, which is gigabit.

Could ohai include a signal in the network/interfaces hashes that a particular interface has been configured gigabit? (Perhaps also indidcating which interfaces are megabit, as those would be more uncommon today.)

**Comment by phreakocious** [comment]
I recently ran into this as well and whipped up a simple ohai plugin that grabs the link speed and PHY type from ethtool as fields 'Speed' and 'Port' in the interfaces section.  https://github.com/phreakocious/ohai-plugins/blob/master/plugins/ethernet_layer_one.rb

**Comment by thommay** [comment]
We'd totally accept a PR that added your ohai plugin to the interfaces section, @phreakocious

**Comment by lamont-granquist** [comment]
@phreakocious if you could merge your plugin into the existing interfaces plugin to add a speed (and maybe duplex for people with really old infrastructure) we'd accept it.

**Comment by phreakocious** [comment]
Will take a look at this.  Thanks.

**Comment by tas50** [comment]
This has been fixed with the PR from @phreakocious It'll go out in the next Ohai release
