### ISSUE TITLE
EC2 plugin doesn't handle data with line breaks

### ISSUE THREAD

**Issue by tas50** [chef/ohai#511]
I'm opening this issue to start the conversation about how this should get handled.  The EC2 metadata endpoint returns some key / value data with line breaks in it.  In particular the security groups have a line break in them.  This results in some pretty funky Ohai data that has to be manipulated before it can be used with a split on the /n.  Any thoughts on how we could resolve this in a backwards compatible way since users are probably splitting it themselves when they need the data now.

**Comment by mcquin** [comment]
@tas50 can you provide an example of what the "funky" returned data looks like?

**Comment by tas50** [comment]
Sorry for the crummy bug report there.  Here's a snippet of the data:

    "network_interfaces_macs": {
      "0a:60:b8:dc:13:e3": {
        "device_number": "0",
        "interface_id": "eni-1234",
        "local_hostname": "something.something",
        "local_ipv4s": "1.1.1.1",
        "mac": "0a:60:b8:dc:13:e3",
        "owner_id": "1234",
        "security_group_ids": "sg-1234\nsg-1234",
        "security_groups": "group1\ngroup2",
        "subnet_id": "subnet-91eb8ee6",
        "subnet_ipv4_cidr_block": "1234",
        "vpc_id": "vpc-1234",
        "vpc_ipv4_cidr_block": "1234"
      }
    },

**Comment by mcquin** [comment]
It would be nice if ohai split that data into an array for you.

Regarding backcompat, it seems the pattern here is to create a `:Foo2` when there are breaking changes to a `:Foo` plugin. I don't know at what point `:Foo2` can replace `:Foo`. I don't want to add a `"parsed_security_groups"` attribute, I think it would cause too much confusion.

**Comment by tas50** [comment]
We actually fixed the security group issue by treating it as an array, but we should mark additional data we find as an array. I've opened a PR for local_ipv4 which can also be 2+ values
