### ISSUE TITLE
Missing memory information for windows systems

### ISSUE THREAD

**Issue by burtlo** [chef/ohai#515]
I googled and found this ticket: https://tickets.opscode.com/browse/OHAI-463

I scanned through the platform specific plugins on Windows and found that the memory is still not being collected.

This information is fairly trivial to collect on Windows 2012R2. I assume that this command works on most of the supported windows platforms but I haven't the experience to know.

```bash
wmic ComputerSystem get TotalPhysicalMemory
```

**Comment by tas50** [comment]
@burtlo I'm closing this out now since we've merged the memory plugin
