### ISSUE TITLE
Cloud/Rackspace attributes not set on Windows Rackspace servers 

### ISSUE THREAD

**Issue by tophercullen** [chef/ohai#519]
As a user, I want to be able to access windows nodes created in rackspace by their public IP. However, the public IP is unavailable because ohai isn't/can't set any of the cloud/rackspace metadata attributes in node[:rackspace], node[:cloud], or node[:cloud_v2].

**Comment by tophercullen** [comment]
This is actually an issue with linux nodes as well. No public address information is available

**Comment by jarosser06** [comment]
Any chance you are using Rackspace OnMetal servers or that your servers are Rackconnected?

**Comment by tophercullen** [comment]
They are VMs but I think they are using rackconnect. It looks like the public IP is even wrong in xen store because, for what ever reason, they change the ip address assignment mid provisioning.

**Comment by jarosser06** [comment]
Yeah the Rackspace Ohai Plugin doesn't fetch a public IP when they are Rackconnected.  Whenever the nodes first come up they are assigned a public IP then Rackconnect automation takes over which disables the public IP and adds the Rackconnect IP.

**Comment by tophercullen** [comment]
I could understand if it was setting the wrong public ip, But its not setting any attributes at all.

**Comment by jarosser06** [comment]
Ohai assumes eth0 is the public net which is true excluding onMetal and Rackconnected servers.  eth0 gets disabled on a Rackconnected server so Ohai doesn't pull the address.  You might want to check out the public_info Ohai plugin and utilize that for the public net.

The Ohai code:
https://github.com/chef/ohai/blob/master/lib/ohai/plugins/rackspace.rb#L127

The plugin
https://github.com/rackspace-cookbooks/ohai_public_info/blob/master/files/default/public_info.rb

I have a rackconnect Ohai plugin that pulls data for V2 but It only pulls the Automation Status.  I'll work on getting better integration for the rackconnect IP :)

https://github.com/jarosser06/ohai-rackconnect/blob/master/rackconnect.rb

**Comment by tas50** [comment]
@jarosser06 Any chance there's a binary or other file present on the windows images that we could key off. We're looking for kernels' on Linux and also provider information using 'xenstore-read vm-data/provider_data/provider'.

**Comment by jarosser06** [comment]
I'm not sure TBH I haven't done much with Windows images on Rackspace infrastructure.

**Comment by tophercullen** [comment]
@tas50 Its been a while since I last provisioned in Rackspace, but to my knowledge that even this store is incorrect in linux (see my previous comment).

**Comment by tas50** [comment]
Turns out there's no real way to gather this information on Windows at the moment. I'm going to close this out unless someone can present a way to gather the information.
