### ISSUE TITLE
zpool plugin should support multiple platforms

### ISSUE THREAD

**Issue by cburroughs** [chef/ohai#529]
https://github.com/chef/ohai/blob/master/lib/ohai/plugins/solaris2/zpools.rb

Is as far as I can tell `solaris2` specific.  ZFS is now avialable in [many more place](http://open-zfs.org/wiki/Distributions).

Initial notes:
- On Linux not all devices start with `c` as the regex currently requires.  (For example, they might start with `ata`.)
- I'm not sure what magic allows `shell_out` to work instead of `Mixlib::ShellOut`

**Comment by lamont-granquist** [comment]
Seems like a pretty easy PR to just expand the list of platforms that this runs on, if its as simple as that.

**Comment by tas50** [comment]
I realized that Chef wasn't detecting my zpool at home so I figured I'd check this out. It's not a huge change to make it happen on Linux. I'm working to make it more robust though so we can get it to work on BSD. Once I get someone with a BSD setup to give me some CLI outputs I'll update this PR 

https://github.com/chef/ohai/pull/1001

**Comment by tas50** [comment]
This has been fixed and will be released in Ohai 13.2
