### ISSUE TITLE
Ohai collects a *lot* of data if you have an OEM Logo set on Windows

### ISSUE THREAD

**Issue by juliandunn** [chef/ohai#533]
If you have an OEM logo set on Windows, Ohai collects a lot of data. [57,657 extra lines](https://gist.github.com/juliandunn/16ac10df350a114a5412#file-windows-ohai-data-json-L134-L57790) of it, in fact, representing every pixel of the OEM logo bitmap.

**Comment by mcquin** [comment]
It appears to be that this has been taken care of: https://github.com/chef/ohai/commit/54b5d408284b51ee47a6c4b2b72c23933a929242

**Comment by juliandunn** [comment]
Indeed!
