### ISSUE TITLE
chef-client hangs (ohai discovery hangs) when a server has a mounted nfs filesystem while the remote host does not respond

### ISSUE THREAD

**Issue by liutc** [chef/ohai#537]
#### Version:

Ohai: 8.0.1
Chef: 12.0.3 (chef-client)
Environment:

CentOS 6.6
AIX 7.1

####  Scenario:

When I have a mounted nfs filesystem, I run chef-client to perform a discovery or change (executing some recipes). If the remote host exporting the nfs directory does not respond (nfs service down, etc.), the chef-client will just hang there.

#### Steps to Reproduce:

1. create a nfs export on one server, e.g. exporting /test_export on "remote_host"
2. mount it on a second server
3. stop the nfs service on the first server
4. run chef-client or ohai on the second server 

#### Expected Result:

The chef-client can run and exit (no matter with error or not).

#### Actual Result

The chef-client hangs. 

#### Root cause

This hang is caused by the command "df" is hanging which is part of the ohai discovery of filesystem (the filesystem plugin). If the remote host does not respond, the df command hangs which further cause the chef-client process hangs.

**Comment by thommay** [comment]
it would seem reasonable to time out the call to `df` after 30 seconds or so

**Comment by thommay** [comment]
(you'll presumably have a zombie df hanging around, but there's not much we can do about that)

**Comment by lamont-granquist** [comment]
closing since #738 is a more general solution

**Comment by liutc** [comment]
Changing the default timeout to 30 seconds can resolve the problem. The issue then is whether the filesystem (or new filesystem2 plugin) can still get some information of the local filesystems. 
 
 
Best Regards,Dr. Tiancheng Liu (刘天成)Cloud Operations TechnologyIBM Research - ChinaPhone: (86-10)58748521Fax: (86-10)58748731Email: liutc@cn.ibm.comAddress: Building 19 Zhongguancun Software Park, 8 Dongbeiwang WestRoad, Haidian District, Beijing, P.R. ChinaBeijing 100193
 
 
----- Original message -----From: Lamont Granquist <notifications@github.com>To: chef/ohai <ohai@noreply.github.com>Cc: Tian Cheng Liu/China/IBM@IBMCNSubject: Re: [ohai] chef-client hangs (ohai discovery hangs) when a server has a mounted nfs filesystem while the remote host does not respond (#537)Date: Thu, Feb 18, 2016 2:49 AM 
closing since #738 is a more general solution
