### ISSUE TITLE
dmi plugin captures data for skipped handles

### ISSUE THREAD

**Issue by caneylan** [chef/ohai#538]
Hi all,

I've noticed an issue in the dmi ohai plugin in which attribute data for skipped handles are added to the last non-skipped handle's data bucket instead of being discarded.  

The plugin parser is a simple state-machine based on the format of the lines.  In the top-level state, the parser will find the Handle lines and determine the type.  Subsequent data lines are parsed and added to the dmi_record object.

```
Handle 0x0100, DMI type 1, 27 bytes
System Information
        Manufacturer: HP
        Product Name: ProLiant DL380p Gen8
        Version: Not Specified
        Serial Number: XXXX
```

The handle parser has a quick check for unrecognized type id numbers, to skip them, and then creates the dmi_record for this new data.  The data lines are added to this object.

```ruby
 elsif handle = handle_line.match(line)
    # Don't overcapture for now (OHAI-260)
    next unless Ohai::Common::DMI::IdToCapture.include?(handle[2].to_i)
    dmi_record = {:type => DMI.id_lookup(handle[2])}
```
...
```ruby
 elsif data = data_line.match(line)
    if dmi_record == nil
      Ohai::Log.debug("unexpected data line found before header; discarding:\n#{line}")
      next
    end
    dmi[dmi_record[:type]][:all_records][dmi_record[:position]][data[1]] = data[2]
```

The bug here is that the short circuit for unrecognized Handles neglects to nil the dmi_record variable. Thus, when the parser sees the subsequent data lines for the "skipped" Handle, it adds their data values into dmi_record, which is still defined from the last successfully recognized Handle.

The following change should resolve the issue:

```ruby
  elsif handle = handle_line.match(line)
     # Don't overcapture for now (OHAI-260)
-    next unless Ohai::Common::DMI::IdToCapture.include?(handle[2].to_i)
+    unless Ohai::Common::DMI::IdToCapture.include?(handle[2].to_i)
+      dmi_record = nil
+      next
+    end
```

**Comment by bcg62** [comment]
maybe this is also the cause of #500 ?

**Comment by thommay** [comment]
@caneylan can you provide a full dmidecode output so that I can test this properly? (or just an example of a handle and info you'd expect to be skipped?
