### ISSUE TITLE
no dmi information on solaris2

### ISSUE THREAD

**Issue by lhandl** [chef/ohai#539]
Hello!

I've installed chef-client 11.14.6 on Solaris 10 (x86 and sparc) with ohai 7.2.4. I'm trying to fetch DMI Information from our solaris systems, but only get an empty hash, when querying DMI information.

root@solaris-host:/ # ohai dmi
{

}

I observe the same behaviour while running chef-shell or chef-client.

Kind regards,
Lothar

**Comment by thommay** [comment]
looks like we ought to use `smbios` to gather this information.
