### ISSUE TITLE
no dmi information on centos

### ISSUE THREAD

**Issue by lhandl** [chef/ohai#542]
Thank you for your fix on Solaris. I'm sorry to disturb again. I've also problems fetching DMI information from Centos.

[root@centos-server~]# ohai dmi
{

}

I'm using Chef client 11.14.6 with ohai 7.2.4 on Centos 6.6.

Could you please have a look at that?

Kind regards,
Lothar

**Comment by thommay** [comment]
centos by default doesn't have dmidecode installed.
When it is installed:

```
[root@ip-172-31-18-181 ~]# cat /etc/redhat-release
CentOS release 6.5 (Final)
[root@ip-172-31-18-181 ~]# rpm -qa dmidecode
dmidecode-2.12-5.el6_5.x86_64
[root@ip-172-31-18-181 ~]# ohai dmi |head
{
  "dmidecode_version": "2.12",
  "smbios_version": "2.4",
```
(this is chef 12, but there's been no change there for a long time)

**Comment by lhandl** [comment]
I'm impressed of your quick reaction. Thank you very much for your help! Installing dmidecode solved my problem on centos.
