### ISSUE TITLE
IPv6 bug in detecting link-local addresses

### ISSUE THREAD

**Issue by rmoriz** [chef/ohai#545]
By RFC4291 2.5.6  FE80::/10 is link-local.

see: 
- https://tools.ietf.org/html/rfc4291#section-2.4
- https://tools.ietf.org/html/rfc4291#section-2.5.6

However OHAI detects  FE80::/10 as public address:

Wrong Test/Detection:
https://github.com/chef/ohai/blob/master/spec/unit/util/ip_helper_spec.rb#L56-L62
https://github.com/chef/ohai/blob/master/lib/ohai/util/ip_helper.rb#L23

This causes link-local addresses to be listed as "public_ipv6_addrs" in cloud_v2 and others. Testable on any IPv6 enabled Digital Ocean Droplet.
https://github.com/chef/ohai/blob/master/lib/ohai/plugins/cloud_v2.rb#L293
https://github.com/chef/ohai/blob/master/lib/ohai/plugins/digital_ocean.rb#L46

example ohai output:

```json

    "cloud_v2": {
      "public_ipv4_addrs": [
        "46.101.1.1"
      ],
      "local_ipv4_addrs": [
        "10.135.1.1"
      ],
      "public_ipv6_addrs": [
        "2a03:b0c0:3:d0::1",
        "fe80::601:52ff:fe96:b201",                <---- WRONG
        "fe80::601:52ff:fe96:b202"                 <---- WRONG
      ],

```

**Comment by mcquin** [comment]
https://github.com/chef/ohai/pull/546
