### ISSUE TITLE
no macaddress on solaris

### ISSUE THREAD

**Issue by lhandl** [chef/ohai#549]
Dear developers,

I recognized, that ohai does not find any macaddress on solaris 10 while an ipaddress is found. I'm using Chef client 11.14.6 and ohai 7.2.4. There's no difference between sparc and x86.

here are some outputs:
 # ohai
{ ...
  "ipaddress": "192.168.3.160",
  "macaddress": null,
  ...
}

 # ohai macaddress
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/lib/ohai/system.rb:191:in `attributes_print': I cannot find an attribute named macaddress! (ArgumentError)
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/lib/ohai/application.rb:94:in `block in run_application'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/lib/ohai/application.rb:93:in `each'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/lib/ohai/application.rb:93:in `run_application'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/lib/ohai/application.rb:70:in `run'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/bin/ohai:42:in `<top (required)>'
        from /usr/bin/ohai:23:in `load'
        from /usr/bin/ohai:23:in `<main>'

Do you have an idea what's going wrong?

Kind regards,
Lothar

**Comment by thommay** [comment]
I can't reproduce this on illumos:

```
14:37 ~ % ohai macaddress                                          thom@scherzo
[
  "10:c3:7b:47:4f:c1"
]
14:37 ~ % uname -a                                                 thom@scherzo
SunOS scherzo 5.11 omnios-a708424 i86pc i386 i86pc
```

can you run: `ohai -l debug macaddress` and paste the output please?

**Comment by lhandl** [comment]
sure:

 # ohai -l debug macaddress
[2015-05-28T16:50:43+02:00] DEBUG: found gateway: 192.168.3.1
[2015-05-28T16:50:43+02:00] DEBUG: found gateway device: ce0
[2015-05-28T16:50:43+02:00] DEBUG: [inet] Using default interface ce0 and default gateway 192.168.3.1 to set the default ip to 192.168.3.160
[2015-05-28T16:50:43+02:00] DEBUG: unable to detect ip6address
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/lib/ohai/system.rb:191:in `attributes_print': I cannot find an attribute named macaddress! (ArgumentError)
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/lib/ohai/application.rb:94:in `block in run_application'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/lib/ohai/application.rb:93:in `each'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/lib/ohai/application.rb:93:in `run_application'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/lib/ohai/application.rb:70:in `run'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.2.4/bin/ohai:42:in `<top (required)>'
        from /usr/bin/ohai:23:in `load'
        from /usr/bin/ohai:23:in `<main>'

 # uname -a
SunOS solaris-host 5.10 Generic_150400-20 sun4u sparc SUNW,Sun-Fire-V890

**Comment by thommay** [comment]
is there any chance you could try with chef 12? just to confirm whether it's fixed there or not?

**Comment by lhandl** [comment]
same behavior in Chef client 12.3.0 with ohai 8.3.0. Can I help with any further input?

**Comment by thommay** [comment]
yeah, if you could show me:
`ohai network/interfaces`
`ifconfig -a`
and
`arp -an`

that would be great. If they're huge or private please feel free to mail them to me: thom at chef dot io.

**Comment by lhandl** [comment]
I've sent you the outputs you requested via email.

**Comment by thommay** [comment]
Thanks. There's something weird going on; I'll dig further into this as soon as I can.
