### ISSUE TITLE
missing runtime dependencies on sigar and plist

### ISSUE THREAD

**Issue by terceiro** [chef/ohai#556]
Currently `plist` and `sigar` are mentioned in the `Gemfile`, but not in `ohai.gemspec`. They are both used at runtime, so they should probably be listed as proper dependencies:

```
$ ack 'require.*(plist|sigar)' lib/ -l
lib/ohai/plugins/sigar/filesystem.rb
lib/ohai/plugins/sigar/cpu.rb
lib/ohai/plugins/sigar/network.rb
lib/ohai/plugins/sigar/memory.rb
lib/ohai/plugins/sigar/network_route.rb
lib/ohai/plugins/sigar/platform.rb
lib/ohai/plugins/darwin/system_profiler.rb
lib/ohai/plugins/network_listeners.rb
lib/ohai/plugins/uptime.rb
lib/ohai/plugins/hostname.rb
```

**Comment by lamont-granquist** [comment]
The sigar plugin is optional and deprecated and should not be in the ohai.gemspec

**Comment by lamont-granquist** [comment]
The plist gem is pure ruby with no obnoxious deps so it could be added.  I think we wind up with it anyway due to chef now having a dep on it.
