### ISSUE TITLE
centos 7 platform not detected on master

### ISSUE THREAD

**Issue by twk3** [chef/ohai#560]
Just a problem in master, not the 8.4.0 release. Running ohai platform reports ```I cannot find an attribute named platform!```

**Comment by maxlazio** [comment]
Looks like this broke it: https://github.com/chef/ohai/compare/8.4.0...master#diff-287bd4842f9ed3193408e40b9e59c099R63

CentOS7 contains `/etc/os-release` so it never reaches the check for Redhat platform

**Comment by danielsdeleo** [comment]
I confirmed the fix with a ChefDK build using master of ohai.
