### ISSUE TITLE
Unable to run Ohai::System.all_plugins within reasonable time on my Windows machine

### ISSUE THREAD

**Issue by klutarevich** [chef/ohai#581]
### Version:
Chef DK 12.3 (Ohai 8.3.0)

### Environment:
Windows 7 64 bit (non-domain joined), Intel i7-2620M 2.7 Ghz, 8Gb RAM

### Scenario:
Trying to see the results generated by Ohai in manual mode

### Steps to Reproduce:
``` ruby
    irb(main):001:0> require 'ohai'
    => true
    irb(main):002:0> Ohai::Config[:plugin_path]
=> ["C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.3.0/lib/ohai/plugins"]
    irb(main):002:0> o = Ohai::System.new
    => #<Ohai::System:0x2857608 @plugin_path="", @data={}, @provides_map=#<Ohai::ProvidesMap:0x28575a8 @map={}>, @v6_dependency_solver={}, @loader=#<Ohai::Loader:0x2857548 @controller=#<Ohai::System:0x2857608 ...>, @v6_plugin_classes=[], @v7_plugin_classes=[]>, @runner=#<Ohai::Runner:0x2857500 @provides_map=#<Ohai::ProvidesMap:0x28575a8 @map={}>, @safe_run=true>>
    irb(main):003:0> o.all_plugins
     .......................
```

### Expected Result:
o.all_plugins should presents collected results in JSON format within reasonable amount of time (<1 min). For example, Windows 2012 R2 servers running Chef client 11.9 gave me just several screens of data within 20 secs.

### Actual Result:
o.all_plugins runs forever spewing tons of data (see the fragment below). I had to terminate irb in order to stop it.
>>>
vider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "TCP/IP Protocol Driver"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_TCPIP\\0000", "device_name"=>"TCP/IP Protocol Driver", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "Security Processor Loader Driver"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_SPLDR\\0000", "device_name"=>"Security Processor Loader Driver", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "Security Driver"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_SECDRV\\0000", "device_name"=>"Security Driver", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "Link-Layer Topology Discovery Responder"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_RSPNDR\\0000", "device_name"=>"Link-Layer Topology Discovery Responder", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "Reflector Display Driver used to gain access to graphics data"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_RDPREFMP\\0000", "device_name"=>"Reflector Display Driver used to gain access to graphics data", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "RDP Encoder Mirror Driver"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_RDPENCDD\\0000", "device_name"=>"RDP Encoder Mirror Driver", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "RDPCDD"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_RDPCDD\\0000", "device_name"=>"RDPCDD", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "QoS Packet Scheduler"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_PSCHED\\0000", "device_name"=>"QoS Packet Scheduler", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "PEAUTH"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_PEAUTH\\0000", "device_name"=>"PEAUTH", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "Performance Counters for Windows Driver"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_PCW\\0000", "device_name"=>"Performance Counters for Windows Driver", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "pciide"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_PCIIDE\\0000", "device_name"=>"pciide", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "Null"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_NULL\\0000", "device_name"=>"Null", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "NSI proxy service driver."=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_NSIPROXY\\0000", "device_name"=>"NSI proxy service driver.", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "NETBT"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_NETBT\\0000", "device_name"=>"NETBT", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "NDProxy"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_NDPROXY\\0000", "device_name"=>"NDProxy", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "NDIS Usermode I/O Protocol"=>{"caption"=>nil, "class_guid"=>nil, "compat_id"=>nil, "creation_class_name"=>nil, "description"=>nil, "device_class"=>"LEGACYDRIVER", "device_id"=>"ROOT\\LEGACY_NDISUIO\\0000", "device_name"=>"NDIS Usermode I/O Protocol", "dev_loader"=>nil, "driver_date"=>nil, "driver_name"=>nil, "driver_provider_name"=>nil, "driver_version"=>nil, "friendly_name"=>nil, "hard_ware_id"=>nil, "inf_name"=>nil, "install_date"=>nil, "is_signed"=>nil, "location"=>nil, "manufacturer"=>nil, "name"=>nil, "pdo"=>nil, "signer"=>nil, "started"=>nil, "start_mode"=>nil, "status"=>nil, "system_creation_class_name"=>nil, "system_name"=>nil, "version"=>nil, "date"=>nil}, "NDIS System Driver"=>{"caption"=>nil, 
<<<

**Comment by mcquin** [comment]
Ohai does collect a lot of data, fortunately or unfortunately (depending on your outlook). All plugins should run fairly quickly, but that is highly dependent on the state of your system. Many users have reported similar issues for various plugins, especially when the attribute being profiled is large. 

Unfortunately, we don't have a good way of dealing with this except to disable the plugins which collect unnecessary data for you. The snippet you provided may be coming from the [Windows `:Drivers` plugin](https://github.com/chef/ohai/blob/8-stable/lib/ohai/plugins/windows/drivers.rb), though that's only a guess since I don't know what the top-level attribute is based on the information you've provided. If you don't need the information collected by this plugin you can add `Ohai::Config[:disabled_plugins] = [ :Drivers ]` to your configuration file. If you do require this information, we'll have to come up with another workaround for you. Possibly a custom plugin which only collects information about the drivers you care about.

> Scenario:
> Trying to see the results generated by Ohai in manual mode

To see what data is collected by Ohai for a specific attribute, you can run `ohai ATTRIBUTE` (e.g., `ohai cpu` will run plugins providing `"cpu"` and display the result). If you would like to see what data is collected by Ohai for a set of attributes, you can run `ohai ATTRIBUTE_1 ATTRIBUTE_2 ... ATTRIBUTE_N`.

Currently the ohai application does not read a configuration file; if you disabled any plugins running `ohai` will still run everything. Something to be aware of. :)
