### ISSUE TITLE
Adjusting fqdn via ohai plugin

### ISSUE THREAD

**Issue by dgoradia** [chef/ohai#607]
I've made a plugin which is just a slightly modified version on the hostname.rb plugin for ohai. The plugin seems to be run via the ohai cookbook but the fqdn isn't updated on the Chef Server. 

```
Ohai.plugin(:FixFqdn) do
  provides 'fqdn'

  collect_data(:windows) do
      require 'wmi-lite/wmi'
      require 'socket'

      wmi = WmiLite::Wmi.new
      ip = wmi.query("Select * from Win32_NetworkAdapterConfiguration WHERE IPEnabled = 'True'").first['ipaddress'].first

      info = Socket.gethostbyname(Socket.gethostname)
      if info.first =~ /.+?\.(.*)/
        fqdn info.first
      else
        fqdn Socket.gethostbyaddr(ip.split('.').map(&:to_i).pack("CCCC")).first
        Chef::Log.warn("ohai-plugin - FQDN: #{fqdn}")
      end
  end
end
```

recipes/default.rb
```
ohai 'reload' do
  action :nothing
end

cookbook_file "#{node['ohai']['plugin_path']}/atlasfqdn.rb" do
  source 'plugins/atlasfqdn.rb'
  notifies :reload, 'ohai[reload]', :immediately
end

include_recipe 'ohai::default'
```

Output of chef-client run
```
...
  * ohai[reload] action reload[2015-08-14T21:57:51-07:00] WARN: ohai-plugin - FQDN: win7tod.fls.domain.net

    - re-run ohai and merge results into node attributes
...
```

It didn't get updated:
```
C:\Users\Tod>ohai fqdn
[
  "win7tod"
]
```

**Comment by mcquin** [comment]
The `ohai` command is running the original hostname plugin. If the machine you are running that command on is managed by Chef (specifically, `recipes/default.rb` has been run on it) you can pass the `ohai` command the path to the directory containing your fdqn plugin. For example, the ohai cookbook places your custom plugins in `/etc/chef/ohai_plugins` by default. If you run `ohai -d /etc/chef/ohai_plugins fqdn` you should see the result you expect.

**Comment by lamont-granquist** [comment]
This is almost more of a SO question than a bug report.  The enhancement that would make this better is captured here:

https://github.com/chef/chef-rfc/blob/master/rfc059-ohai-cookbook-segment.md

We should definitely support dropping a custom plugin that overwrites a built-in one and making sure the cookbook ohai run overwrites it as part of implementing that RFC
