### ISSUE TITLE
finding rack and enclosure

### ISSUE THREAD

**Issue by lancepowell** [chef/ohai#614]
In previous ohai versions I was able to gather the rack name using this:

`node['dmi']['oem_strings']['rack_name']`

In ohai 8.5.0 i see the change to only gather certain sets of data:

https://github.com/chef/ohai/blob/8-stable/lib/ohai/common/dmi.rb#L74

Running dmidecode, what I'm trying to find is dmi type 204, which would fall to the if statement below and set it to:

`oem_data_204`

I'm not sure why it was pulling back in oem_strings in chef 11/ohai 7 but now in 8, we don't see the rack or enclosure info anywhere in ohai. Do we need to modify the IdToCapture and add oem_data_204?

**Comment by tas50** [comment]
I think the real solution here is to allow for configuration of the values as noted in the comment with the code you linked to.  That would allow people to bring in the various oem codes without blowing up the size of Ohai data with all codes.  I'm marking this as an enhancement and I'll see how complex of a change that would be to implement.

**Comment by lamont-granquist** [comment]
feels like this could be handled by a custom ohai plugin as well.

**Comment by tas50** [comment]
@lancepowell I'm going to close this bug out at this point. I think @lamont-granquist has it right here. This is really something you should do with a custom ohai plugin since where that data is stored is going to different between vendors and orgs.
