### ISSUE TITLE
ohai probe of lsblk causes hang on systems with dead paths

### ISSUE THREAD

**Issue by dreamnite** [chef/ohai#622]
I originally opened this as a Chef support ticket, 5889.

I have a system which is using iscsi storage. When a path to that storage dies (In our original case, due to a reconfiguration of the iscsi system), the lsblk probe done by ohai hangs. 

I have tracked this down to lsblk being called as follows: 
 execve("/bin/lsblk", ["lsblk", "-r", "-n", "-o", "NAME,FSTYPE"], [/* 48 vars */]) = 0 

The FSTYPE appears to make probe the filesystems, from what I can tell by passing a -p flag to blkid. This low level probe locks on the dead paths causing ohai to never return, causing the chef-client to be unable to continue. 

I also noticed in libs/ohai/plugins/linux/filesystem.rb if lsblk is not present on the system, it reverts to a blkid -s TYPE, which does not show the same hangs.

So at this point for a workaround, I can A) remove lsblk (unsure what else may use it) B) Disable the filesystem plugin and lose the data gathered or C) temporarily patch the have_lsblk  variable to report false (not sure if this loses any information).

Any thoughts on a proper solution?

**Comment by lamont-granquist** [comment]
#738 should fix this kind of problem in the general case.
