### ISSUE TITLE
EC2 CNAMEs broken with multiple IPs

### ISSUE THREAD

**Issue by davidjh** [chef/ohai#645]
To support multiple EC2 IPs, it would be preferable to have an array rather, than a concatenated string, so CNAME can use first element. 

Here's an example of how it is currently w/ :
"ec2": "public_hostname": "ec2-52-32-165-31.us-west-2.compute.amazonaws.comec2-52-32-138-27.us-west-2.compute.amazonaws.com",

**Comment by tas50** [comment]
@davidjh What version of Ohai is this occurring with?

**Comment by tas50** [comment]
Closing this out due to lack of response. If this is still  an issue feel free to open it back up against the latest Ohai release.
