### ISSUE TITLE
default_interface / ipaddress mismatch

### ISSUE THREAD

**Issue by ms2scale** [chef/ohai#646]
Running ohai on an ec2 device with an additional network interface. 

default_interface is detected as eth0, which is fine (ohai output)

```
"default_interface": "eth0",
"default_gateway": "172.31.0.1"
```

The ipaddress which is reported is the one which is attached to eth1 which is not that useful because the additional interface is supposed to be moved to another machine. 

I guess ohai is confused by multiple default routes which might occur in the setup.

The ipaddress reported by ohai should match the default interface, or tell me why this is a bad idea.

**Comment by tas50** [comment]
@ms2scale What version of ohai is this occurring on?

**Comment by tas50** [comment]
Closing this out due to lack of response. We've cleaned up a few major bugs in the network detection logic that may have resolved this. Feel free to open it up if you're still seeing the issue.
