### ISSUE TITLE
undefined method `[]=' for #<Ohai::System:0x000000019638a8> (NoMethodError)

### ISSUE THREAD

**Issue by brianjmurrell** [chef/ohai#661]
Hi,

I'm trying to use Ohai outside of Chef to get some general information about the platform it is being run on.

Somewhere between 0.5.8 (yes, I know, very old) and 7.0.4 trying to do:

```
ohai = Ohai::System.new
ohai.all_plugins
...
tmp = ohai.clone
tmp[:platform] = "el"
```

started generating the error:

```
platform_info:32:in `build_ok?': undefined method `[]=' for #<Ohai::System:0x000000019638a8> (NoMethodError)
	from platform_info:85:in `<main>'
```

So it seems that assigning a value to an ohai attribute is no longer allowed?  Or should it just be done differently in 7.0.4?

**Comment by mcquin** [comment]
Assigning a value to an ohai attribute outside of a plugin is no longer supported.

Ohai attributes are stored in the `data` data structure of the `Ohai::System`. This data structure is [readable and writable](https://github.com/chef/ohai/blob/master/lib/ohai/system.rb#L36). Modifying your example slight, you can assign values to an attribute like this:

```ruby
ohai = Ohai::System.new
ohai.all_plugins
...
tmp = ohai.clone
tmp.data[:platform] = "el"
```

`tmp[:platform]` should return `"el"`.

**Comment by brianjmurrell** [comment]
Thanks!
