### ISSUE TITLE
Detect Hyper-V guests running Windows

### ISSUE THREAD

**Issue by tas50** [chef/ohai#664]
I added the logic to properly detect Hyper-V guests running Linux.  We just need to move that same logic over to Windows.

**Comment by rdean716** [comment]
Is the work required for Windows guests still outstanding?  If so, I will try to take a look at it.

**Comment by tas50** [comment]
There's still work to be done improving overall VM guest detection on windows. Take a look at https://github.com/chef/ohai/blob/master/lib/ohai/plugins/windows/virtualization.rb

**Comment by rdean716** [comment]
Will do!  Thanks

**Comment by tas50** [comment]
If you want to add detection of Xen while you're in there that'd be great. Here's the output of win32_bios on a Xen host:


SMBIOSBIOSVersion : 4.2.amazon
Manufacturer      : Xen
Name              : Revision: 1.221 
SerialNumber      : ec2b487f-d9ed-7d17-c7c0-1d4599d6c1da
Version           : Xen - 0

**Comment by tas50** [comment]
This was released in 8.23
