### ISSUE TITLE
Get ipaddress for docker container

### ISSUE THREAD

**Issue by tmaier** [chef/ohai#686]
Docker containers might not have ifconfig.

Ohai should use an alterntive approach to get the ipaddress. E.g. http://stackoverflow.com/questions/27670495/can-i-get-ip-address-inside-my-docker-container

**Comment by lamont-granquist** [comment]
I would actually vote to close this.  The alternative solutions in that stackoverflow question involve installing 'ifconfig' or 'ip' (the right solution IMO, but which is not really a solution).  Or else parsing /etc/hosts, which is the kind of brittleness which is going to be fraught with peril.  Or else hitting various metadata endpoints for whichever cloud service you are on, which we already do, and which you should be able to recover already from other ohai data.  So I don't see a truly useful solution here other than installing ifconfig into your docker container.

**Comment by rwcee** [comment]
@tmaier @lamont-granquist - This appears to have been fixed in the following commit: https://github.com/chef/ohai/commit/c509235734d49c44f9e23ea08f941be7972c848f

**Comment by tas50** [comment]
Closing this out based on @rwcee's comment. Feel free to keep it going if you're still having issues.
