### ISSUE TITLE
EC2 autodetection is broken

### ISSUE THREAD

**Issue by mfischer-zd** [chef/ohai#691]
EC2 instances no longer have a MAC address that matches the pattern provided (`fe:ff:ff:ff:ff:ff`) so the `has_ec2_mac?` function is no longer reliable.

So, for now, the only way to get Ohai to provide EC2-related attributes is to provide a hint file (usually `/etc/chef/ohai/hints/ec2.json`) with an empty JSON object in it.

**Comment by tas50** [comment]
In a VPC the current MAC address detection is definitely broken.  We should expand our "looks like ec2" logic to include dmesg output on Linux which includes a mention of Amazon.  There's probably something similar on Windows.

**Comment by tas50** [comment]
https://github.com/chef/ohai/pull/711 should fix this
