### ISSUE TITLE
Incorrect output of os_version on AIX

### ISSUE THREAD

**Issue by aklyachkin** [chef/ohai#693]
### Version

    # lslpp -L chef
      Fileset                      Level  State  Type  Description (Uninstaller)
      ----------------------------------------------------------------------------
      chef                      12.5.1.1    C     F    The full stack of chef
    # ohai --version
    Ohai: 8.7.0

### Environment

AIX 6.1 or 7.1

### Steps to reproduce

    # ohai os
    [
      "aix"
    ]
    # ohai os_version
    [
      "1"
    ]

### Expected result

    # ohai os_version
    [
      "6.1"
    ]

or

    # ohai os_version
    [
      "6.1.0.0"
    ]

or

    # ohai os_version
    [
      "6100-07"
    ]

or 

    # ohai os_version
    [
      "6100-07-00-0000"
    ]

### Actual result

is always 1. 

The file /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.7.0/lib/ohai/plugins/aix/kernel.rb uses uname command to determine the version and the release of AIX. The AIX command uname -v, which supposes to return the version, returns in fact release - 1 from 6.1 or 7.1. The proper command to determine release level of AIX is oslevel. Without any options it returns the value I personally would expect as os_version in ohio, e.g.:

    # oslevel
    6.1.0.0

with the option *-r* it returns "release", in fact - technology level of AIX. E.g. for AIX 6.1 TL7 it is:

    # oslevel -r
    6100-07

with the option *-s* it returns the latest installed service pack. E.g. for AIX 6.1 TL7 SP0 it is:

    # oslevel -s
    6100-07-00-0000

**Comment by tas50** [comment]
@aklyachkin Thanks for the super detailed report.  This information is very useful.  I'm going to see if I can get access to an AIX box here to try to fix this.  Doesn't look too tricky.

**Comment by thommay** [comment]
ping @chef/client-aix
