### ISSUE TITLE
Empty Result Running Windows 10

### ISSUE THREAD

**Issue by PatrickWalker** [chef/ohai#701]
Hey

Having an issue running Chef Unit tests which I *think* is caused by empty result set from ohai.

On running Ohai I get the following output
{

}

Any ideas?

Version is 8.8.1 and the user should be a local admin etc. I'm not passing any command line arguments which I'm guessing may be part of the cause. 

Futher Details : 
It seems to be discovering the correct, or I assume correct, plugin directory
`Plugin path C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ohai-8.8.1/lib/ohai/plugins`
I've also tried supplying a command line argument for directory to windows child folder under that.

The loader seems to be aware of both but unable to find any providers both v6 and v7

**Comment by PatrickWalker** [comment]
Looks like it's
` Dir[File.join(ChefConfig::PathHelper.escape_glob(plugin_dir), "**", "*.rb")].map do |file|`
That is causing me issues. This is an empty enumerator. That's because seemingly of backslashes in the path

Now from debugging it seems like its the PathHelper that's putting it in because if I change it to
`Dir[File.join(plugin_dir, "**", "*.rb")].map do |file|`

It does run successfully

**Comment by PatrickWalker** [comment]
I downgraded to Ruby 2.0.0 from 2.2.3 and it seems to work now. The IRB still seems unhappy with using \\ in a DIR[] call but as I said it is working in 2.0.0 Ruby

**Comment by mcquin** [comment]
There is a PR in chef that I think should fix the path escaping and globbing. https://github.com/chef/chef/pull/4195

**Comment by PatrickWalker** [comment]
Thanks.

**Comment by lamont-granquist** [comment]
fixed by #747 ?

there may be remaining issues with escape_glob vs escape_glob_dir but not that i can see in this repo and those would be chef/chef bugs...
