### ISSUE TITLE
GCE autodetection broken if ISP intercepts NXDOMAINs

### ISSUE THREAD

**Issue by ayanich** [chef/ohai#706]
In the case where an ISP's DNS servers hijack NXDOMAIN requests, ohai ends up marking a node as gce. Perhaps looking and verifying some keys would be more foolproof?

**Comment by thommay** [comment]
#736 might well help here

**Comment by tas50** [comment]
I believe we probably solved this in the latest chef/ohai combo.  Can you give a try and open this back up if it's still a problem @ayanich
