### ISSUE TITLE
Not detecting java openjdk 1.8

### ISSUE THREAD

**Issue by davidnewman** [chef/ohai#726]
It looks like there is a bug in the java.rb plugin where the version string is not correctly parsed for openjdk version 1.8.
I have tested against ohai version 8.10.0 on a CentOS 6.7 system and observered the following:
```
$ sudo yum install -y java-1.7.0-openjdk
$ java -mx64m -version
java version "1.7.0_95"
OpenJDK Runtime Environment (rhel-2.6.4.0.el6_7-x86_64 u95-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
Note the first line of output for openjdk 1.7.
This is what you see for openjdk 1.8:
```
$ sudo yum install -y java-1.8.0-openjdk
$ java -mx64m -version
openjdk version "1.8.0_71"
OpenJDK Runtime Environment (build 1.8.0_71-b15)
OpenJDK 64-Bit Server VM (build 25.71-b15, mixed mode)
````
Again, note the first line of output.
The issue is with the following regex in java.rb:
`/java version \"([0-9\.\_]+)\"/`
Because the version string output for openjdk 1.8 has changed, the regex fails to capture the version number and the java information is not detected even though java is installed.
The fix is:
`/(?:java|openjdk) version \"([0-9\.\_]+)\"/`
I am going to pull request against this issue, but I am not a ruby dev, so you may want to figure out a better fix if appropriate.

**Comment by davidnewman** [comment]
Pull request is here: https://github.com/chef/ohai/pull/727

**Comment by tas50** [comment]
Fixed on master now
