### ISSUE TITLE
Remove sigar from the top level plugins

### ISSUE THREAD

**Issue by tas50** [chef/ohai#729]
We have alternative code paths depending on if sigar is installed or not.  This seems unecessary and likely to break people as a system with sigar installed will more than likely produce different results than those from a vanilla omnibus build.  We should remove it from high level plugins and leave the single use in hpux.  This is a breaking change that should probably be reserved for Ohai 9.0

**Comment by juliandunn** [comment]
Since HP-UX isn't supported anymore by Chef/Ohai I'm sure you could just rip out sigar.

**Comment by tas50** [comment]
Merged to master
