### ISSUE TITLE
Drop default mixlib-shellout timeout down to something more appropriate for ohai

### ISSUE THREAD

**Issue by lamont-granquist** [chef/ohai#738]
I'd say roughly 30 seconds?  If we don't get a result from any ohai command that is probably too long.

The default mixlib-shellout timeout is geared towards general purpose chef-client usage, where we might be installing an application that compiles half the native gems on rubygems or something.   Nothing that ohai launches should take more than about 30 seconds or its pretty busted.

**Comment by smurawski** [comment]
:+1:

**Comment by thommay** [comment]
we should definitely drop the time out, but let's test across the board to see what's appropriate given the ... crankiness ... of some of our platforms

**Comment by lamont-granquist** [comment]
I think 30 should most likely be the default, and we should tune the odd plugin higher after we determine it needs it.

**Comment by danielsdeleo** [comment]
I'm cool with this

**Comment by tas50** [comment]
#732 will resolve this.  I just need to write some tests for it.

**Comment by tas50** [comment]
This has been merged to master
