### ISSUE TITLE
Ohai reporting Manfacturer as UNKNOWN

### ISSUE THREAD

**Issue by jennyfountain** [chef/ohai#741]
CentOS 6.6
# dmidecode 2.12
SMBIOS 2.8 present.

Handle 0x0006, DMI type 1, 27 bytes
System Information
	Manufacturer: HP
	Product Name: ProLiant DL360 Gen9
	Version: Not Specified

Linux xxxx 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

xxxxxxx:
  dmi.system:
    all_records:
      Array Handle:             0x0008
      Asset Tag:                Not Specified
      Bank Locator:             Not Specified
      Configured Clock Speed:   Unknown
      Configured Voltage:        Unknown
      Data Width:               64 bits
      Ending Address:           0x000000207FFFFFFFk
      Error Correction Type:    Single-bit ECC
      Error Information Handle: Not Provided
      Family:                   ProLiant
      Form Factor:              DIMM
      Header and Data:
        D3 07 24 00 04 00 00: 
      Location:                 System Board Or Motherboard
      Locator:                  PROC 2 DIMM 12
      Manufacturer:             UNKNOWN  <---
      Maximum Capacity:         768 GB
      Maximum Voltage:           Unknown
      Minimum Voltage:           Unknown
      Number Of Devices:        12
      Part Number:              NOT AVAILABLE
      Partition Width:          1
      Physical Array Handle:    0x0008
      Product Name:             ProLiant DL360 Gen9

**Comment by tas50** [comment]
@jennyfountain Thanks for getting this bug in and sorry for taking so long to get back to you. I didn't mean to blackhole your list discussion into a GH issue. From your dmidecode and ohai output it definitely seems like we're not decoding the system information correctly. I'll see what I can find.

**Comment by tas50** [comment]
@jennyfountain Can you post a gist or e-mail (tsmith[AT]chef.io) me the output of 'ohai -l debug'.

**Comment by tas50** [comment]
This was resolved in an e-mail thread by upgrading to the latest Chef/Ohai.  The issue was seen in Ohai 7.X.
