### ISSUE TITLE
Create a mixin for http connections

### ISSUE THREAD

**Issue by tas50** [chef/ohai#762]
We've cargo culted the code the ec2 metadata mixin in multiple places.  The logic is fairly generic and we should use it anytime someone wants to make a http call:

Try to open a socket
If the socket can be opened then fetch the http data
Handle errors in the various places we can fail
Debug logging everywhere

**Comment by lamont-granquist** [comment]
dup of #712?

**Comment by tas50** [comment]
712 might not be needed after this, but it depends on the scope of the http mixin.

**Comment by tas50** [comment]
Initial mixin has been created and is being used for the cloud plugins now
