### ISSUE TITLE
EC2 plugin fails to detect Windows

### ISSUE THREAD

**Issue by meringu** [chef/ohai#781]
## Description

Ohai consistently fails to detect it is running on an EC2 instance in windows.

This line could be problematic, https://github.com/chef/ohai/blob/master/lib/ohai/plugins/ec2.rb#L33

## Ohai Version

    ohai -v
    Ohai: 8.8.1

## Platform Version

    Windows 2012r2

## Ohai Output

When running

    ohai -l debug ec2

I get

    [2016-03-22T22:09:45+00:00] DEBUG: has_ec2_mac? == false
    [2016-03-22T22:09:45+00:00] DEBUG: looks_like_ec2? == false
    c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.8.1/lib/ohai/system.rb:193:in `attributes_print': I cannot find
     an attribute named ec2! (ArgumentError)
        from c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.8.1/lib/ohai/application.rb:94:in `block in run_application'
        from c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.8.1/lib/ohai/application.rb:93:in `each'
        from c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.8.1/lib/ohai/application.rb:93:in `run_application'
        from c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.8.1/lib/ohai/application.rb:78:in `run'
        from c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.8.1/bin/ohai:42:in `<top required)>'
        from c:/opscode/chef/bin/ohai:22:in `load'
        from c:/opscode/chef/bin/ohai:22:in `<main>'

cc @zl4bv

**Comment by mcquin** [comment]
It'd be great to get automatic detection of EC2 for windows. :) 

In the meantime, you can work around this by [adding an ec2 hint to your node](http://geekblood.com/2015/03/13/enabling-ec2-metadata-in-ohai/) before your next chef-client run. There's a little [documentation on hints](https://docs.chef.io/ohai.html#hints), too.

**Comment by tas50** [comment]
@meringu Hints are always going to be your best bet, but I've included improved auto detection for EC2 in #793 which includes detection of AWS Windows instances based on the owner data.  This won't detect custom AMIs, but it will detect anything provided by Amazon. It should be included with the next Chef release if all goes as planned.
