### ISSUE TITLE
Create a helper for accessing Mash data

### ISSUE THREAD

**Issue by tas50** [chef/ohai#794]
It's difficult to check deep Mashes right now without throwing errors that need to be rescued.  Instead of writing repetitive defense code around this it would be nice to create a helper for accessing the methods.  If the attribute data isn't there it would log and return nil, otherwise it'd return the data.  This would prevent the need for things like this:

```ruby
    begin
      if kernel[:os_info][:organization] =~ /Amazon/
        Ohai::Log.debug("ec2 plugin: has_amazon_org? == true")
        true
      end
    rescue NoMethodError
      Ohai::Log.debug("ec2 plugin: has_amazon_org? == false")
      false
    end
  end
```

**Comment by mcquin** [comment]
Notes: We have checkers and fetchers for top-level attributes, but no helpers for subattributes.
