### ISSUE TITLE
EC2 OHAI plugin that has nested information

### ISSUE THREAD

**Issue by EZtheOG** [chef/ohai#825]
## Description

I am moving from Puppet to Chef and in Puppet our manifests have a LOT of AWS EC2 specific logic. Specifically, on our VPN nodes we have a template that uses things like:
`vpn::config::name           =           "{::hostname_full}.conf"`
`vpn::config::public          =           "%{::public_ip}"`

and then do the lookup via facter and put it in the code.

I was hoping to replicate this implementation in chef. Now, some of the things that are challenging to grab info of are:
subnet_ipv4_cidr_block
subnet_id
vpc_ipv4_cidr_block

The reasons for the difficulty are that you need to pull the MAC address - so in your template variable you can do:
`variables ( :var =>  node['ec2']['network_interfaces_macs']['ACTUAL_MAC']['subnet_ipv4_cidr_block']`

Now, this doesn't seem to work - is there a way to remove the nested MAC address?

I just feel like you should be abled to do `node['ec2']['subnet_id']`
## Ohai version

8.11.1
## Platform Version

Amazon Centos 
## Ohai Output

```
 "ec2": {
    "ami_id": "ami-08111162",
    "ami_launch_index": "0",
    "ami_manifest_path": "(unknown)",
    "block_device_mapping_ami": "/dev/xvda",
    "block_device_mapping_root": "/dev/xvda",
    "hostname": "ip-10-0-100-107.ec2.internal",
    "instance_action": "none",
    "instance_id": "i-278e9ba3",
    "instance_type": "t2.micro",
    "local_hostname": "ip-10-0-100-107.ec2.internal",
    "local_ipv4": "10.0.100.107",
    "mac": "0a:0a:4d:bb:34:4d",
    "metrics_vhostmd": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
    "network_interfaces_macs": {
      "0a:0a:4d:bb:34:4d": {
        "device_number": "0",
        "interface_id": "eni-4d13420c",
        "local_hostname": "ip-10-0-100-107.ec2.internal",
        "local_ipv4s": "10.0.100.107",
        "mac": "0a:0a:4d:bb:34:4d",
        "owner_id": "480352787924",
        "security_group_ids": "sg-22bc4b44",
        "security_groups": "Internal Traffic",
        "subnet_id": "subnet-a96ffede",
        "subnet_ipv4_cidr_block": "10.0.100.0/23",
        "vpc_id": "vpc-fooBAR",
        "vpc_ipv4_cidr_block": "10.0.0.0/16"
      }
```

**Comment by mcquin** [comment]
As long as `ACTUAL_MAC` evaluates to the string `"0a:0a:4d:bb:34:4d"`, you should be able to access the subnet ID by using `node['ec2']['network_interfaces_macs'][ACTUAL_MAC]['subnet_ipv4_cidr_block']` (note: no `''` around `ACTUAL_MAC`).

**Comment by tas50** [comment]
Closing based on @mcquin's response
