### ISSUE TITLE
8.19.1 issue with `configured?` method not being found on Logger

### ISSUE THREAD

**Issue by crouch6** [chef/ohai#865]
## Description

We use chef in our systems to provision boxes and when updating chef, it grabs the latest ohai. As of this weekend (13/08/2016), when we ran chef-client, we only got the error:

`NoMethodError: undefined method 'configured? for #<MonoLogger:0x007fbe44a345a8>`

 with no stack trace. We eventually found it was coming from ohai.

We conjecture that the latest refactoring of the configured? method into Mixlib::Log hasn't taken perhaps? So when it is called in lib/ohai/system.rb#L223, it isn't defined.

## Ohai Version

We were using the latest version of 8.19.1

## Platform Version

We are using 
Linux version 3.19.0-66-generic (buildd@lgw01-40) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #74~14.04.1-Ubuntu SMP

## Ohai Output

NoMethodError: undefined method 'configured? for #<MonoLogger:0x007fbe44a345a8>

**Comment by tas50** [comment]
You should be able to resolve this by updating to mixlib-log 1.7.1. We'll get a fix into ohai to require this version. That part of the migration of mixlib-log was missed.

**Comment by crouch6** [comment]
worked a treat.

**Comment by tas50** [comment]
Opening this for tracking on the perm fix
