### ISSUE TITLE
Uptime Plugin Sporadically Hangs

### ISSUE THREAD

**Issue by glasschef** [chef/ohai#875]
## Description

Sometimes the chef-client on Windows will hang during Ohai's uptime checks for an unreasonable amount of time (10s of minutes)

The culprit appears to be the calls to `Win32_PerfFormattedData_PerfOS_System`: https://github.com/chef/ohai/blob/80c91e74ac403959d54c9f15b1aa7a3c4fc4bd8b/lib/ohai/plugins/uptime.rb#L99

This seems to be a bug in the actual Windows WMI service  https://social.msdn.microsoft.com/Forums/vstudio/en-US/afa9b501-63f6-4968-ba44-0b44f49d082c/managementobjectsearcher-vs-getwmiobject-vs-wbemtest?forum=netfxbcl

Calling it directly from 64-bit powershell on an affected system will hang just like the Ohai calls, but by using the 32-bit implementation (and hence hitting the legacy 32-bit WMI API) the call works just fine.

The code in this previously-closed issue appears to be a decent workaround, calling `'Win32_OperatingSystem'` instead of `Win32_PerfFormattedData_PerfOS_System` :  https://github.com/chef/ohai/issues/619

Maybe that can be used instead?
## Ohai Version

8.19.2
## Platform Version

Windows 2008 R2, SP1.
## Ohai Output

No helpful output from Ohai, it just hangs for 10s of minutes

**Comment by thommay** [comment]
@mwrock @chef/client-windows  PTAL :)

**Comment by btm** [comment]
Filed internally as CLOGENG-391.

**Comment by tas50** [comment]
Closing as this was resolved and shipped
