### ISSUE TITLE
ohai no longer prints debug info in standalone executions

### ISSUE THREAD

**Issue by jaymzh** [chef/ohai#878]
## Description

When I run `ohai -l debug` I expect to see plugin failures.

But I do not.
## Ohai Version

8.19.1.

Chef 12.13.37
## Platform Version

CentOS7
## Ohai Output

N/A

**Comment by tas50** [comment]
The log file location flag seems to be broken as well

**Comment by erikng** [comment]
This really makes it hard to debug Ohai and contribute code.

**Comment by tas50** [comment]
This commit cause the logging to not be reconfigured with the CLI arguments, which breaks the CLI logging configs:

https://github.com/chef/ohai/pull/863/files#diff-dee5766eb9ab7555535dae03a4674f28R223

If you comment out the return line things work, but I know there was some backstory as to why we did this. @thommay can probably provide the backstory.
