### ISSUE TITLE
ohai mount size bug with duplicate mount points

### ISSUE THREAD

**Issue by Zhann** [chef/ohai#880]
## Description

If a filesystem is mounted multiple times (cfr. with Docker):

```
root@git-004:~# mount | grep vda2
/dev/vda2 on / type ext4 (rw,relatime,data=ordered,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
/dev/vda2 on /var/lib/docker/299151.299151/aufs type ext4 (rw,relatime,data=ordered,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
```

only the first of those duplicate mount points will get usage stats https://github.com/chef/ohai/blob/80c91e74ac403959d54c9f15b1aa7a3c4fc4bd8b/lib/ohai/plugins/linux/filesystem.rb#L86:

```
node.filesystem.select do |k,v|
  v["mount"] == "/" && v["kb_size"]
end.values.first["kb_size"]
```

and other attributes will get mixed.
## Ohai Version

tested on 7.4.0 and master
## Platform Version

Debian 8.2
## Ohai Output

```
{
  "/dev/vda2": {
    "kb_size": "82341228",
    "kb_used": "50379892",
    "kb_available": "28392816",
    "percent_used": "64%",
    "mount": "/var/lib/docker/299151.299151/aufs",
    "total_inodes": "5222400",
    "inodes_used": "799398",
    "inodes_available": "4423002",
    "inodes_percent_used": "16%",
    "fs_type": "ext4",
    "mount_options": [
      "rw",
      "relatime",
      "data=ordered",
      "jqfmt=vfsv0",
      "usrjquota=aquota.user",
      "grpjquota=aquota.group"
    ]
  },

<................>

  "vda2": {
    "fs_type": "ext4",
    "uuid": "cc42b060-4483-4413-8d84-c16b197fa3ce"
  },
  "rootfs": {
    "mount": "/",
    "fs_type": "rootfs",
    "mount_options": [
      "rw"
    ]
  }
}
```

**Comment by mcquin** [comment]
In 8.5.0 we introduced a `Filesystem2` plugin which handles this case. A description of how it works is here: https://github.com/chef/ohai/pull/559. 

We currently treat the `Filesystem` plugin as deprecated. Please upgrade Ohai and use `Filesystem2`.

**Comment by tas50** [comment]
This is resolved in recent Ohai releases. Upgrade to Chef 12 and this should magically go away.
