### ISSUE TITLE
'block_devices' gets `rotational` wrong

### ISSUE THREAD

**Issue by jaymzh** [chef/ohai#903]
## Description

ram devices and loop devices both show up as rotational.

## Ohai Version

8.19.1

## Platform Version

CentOS 6 and CentOS 7

## Ohai Output

```
    "ram0": {
      "size": "32768",
      "removable": "0",
      "rotational": "1",
      "physical_block_size": "512",
      "logical_block_size": "512"
    },
...
    "loop0": {
      "size": "0",
      "removable": "0",
      "rotational": "1",
      "physical_block_size": "512",
      "logical_block_size": "512"
    },
```

**Comment by tas50** [comment]
This comes down to our incorrect use of the /sys/block/loop0/queue/rotational. This is not an informational value, but a tunable for the system. The OS *may* get it right, but the value allows you to instruct the OS to treat it as a non-rotational disk if you know it is in fact one.

https://lwn.net/Articles/408428/

I'm open to a better way of determining this information as this one is pretty flawed.

**Comment by tas50** [comment]
Closing this one out since it appears to be an OS issue not a Chef issue
