### ISSUE TITLE
CPU model_name is returning CPU description instead of name

### ISSUE THREAD

**Issue by ocsi01** [chef/ohai#904]
## Description

In ohai/lib/ohai/plugins/windows/cpu.rb:
`cpu[current_cpu]["model_name"] = processor["description"]`

The description field has a different result compare to what the "model_name" contains under the linux implementation:
Name: Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz	(Windows)
Description: Intel64 Family 6 Model 63 Stepping 2        (Linux)

[http://www.c-sharpcorner.com/blogs/getting-details-about-your-processor-by-using-win32processor-class](url)

## Ohai Version

8.21

## Platform Version

Windows

## Suggestion

`cpu[current_cpu]["model_name"] = processor["name"]`

**Comment by tas50** [comment]
@ocsi01 Any chance you can put together a PR to fix this?
