### ISSUE TITLE
Dynamic data is not collected

### ISSUE THREAD

**Issue by Fodoj** [chef/ohai#906]
## Description

In addition to meta-data and userdata EC2 also provides "dynamic" data (not sure why it's called dynamic though). One extra useful attribute that it has, and that seems to be not available in other sources, is AWS account id (try running `curl http://169.254.169.254/latest/dynamic/instance-identity/document`). It is possible to fetch account id from the instance that has IAM role attached (by parsing ARN of the role) but for instances without any IAM role this dynamic data is the only way to figure out to which account it belongs to.

## Ohai Version

8.21.0

**Comment by tas50** [comment]
Fixed in #907
