### ISSUE TITLE
Erlang detection broken for < 17

### ISSUE THREAD

**Issue by cheeseplus** [chef/ohai#932]
## Description

Existing Erlang detection only works for Erlang 17+ with #916

## Example

This the shell commands we execute:

```
# Erlang 16B03 / Ubuntu 14.04
$ erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().'

Erlang R16B03 (erts-5.10.4) [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]

Eshell V5.10.4  (abort with ^G)
{"init terminating in do_boot",{{badmatch,{error,enoent}},[{erl_eval,expr,3,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```

This is because the releases file and $MAJ.$MIN format were only addd in Erlang 17. The safe command across all versions is:

`erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'`

but this only returns $MAJ for 17+ so we'll need to do another call to get the releases file if we know it's 17+.

**Comment by tas50** [comment]
I think we're going to won't fix this at this point since Erlang 16 is 4 years old at this point.

**Comment by cheeseplus** [comment]
Somewhere I have a branch fixing it but also probably not a huge deal either way as noted. Let it die.

**Comment by tas50** [comment]
I'm not sure if it's worth the extra code at this point.
