### ISSUE TITLE
ohai failures are too soft

### ISSUE THREAD

**Issue by hfinucane** [chef/ohai#956]
## Description

A Chef run on an oversubscribed-on-memory server failed in a dangerous way. It looks like the network plugin failed- probably because of a fork failure, because of low memory- but the error was swallowed, and our Chef cookbooks are not super defensive about Ohai attributes, and we dutifully wrote empty strings and 'localhost.localdomain' into config files, restarted services, and eventually failed when a Chef resource failed with `Caused by Errno::ENOMEM: Cannot allocate memory - fork(2)`.

It looks like the root of the problem is that [`shell_out`](https://github.com/chef/ohai/blob/master/lib/ohai/mixin/command.rb#L29) does not call `error!`. I do worry that tolerating soft failure might be important to the normal functioning of Ohai though. Is there something we can do to ask Ohai to be more conservative from the Chef side? We use automatic attributes everywhere, and I don't know how feasible rewriting everything to be super defensive is going to be.

## Ohai Version

Ohai 8.21.0, Chef 12.16.42

## Platform Version

CentOS 6

## Ohai Output

```
[ WARN]: unable to detect ipaddress
```

**Comment by cheeseplus** [comment]
The desire is straightforward enough but as you surmise, soft failure is ABSOLUTELY critical to running Ohai in the context of a chef-client run as if Ohai blows up with an exception the whole thing comes crashing down.

This is to say there is very little we can do to prevent these things as that resilience to individual plugin failure is somewhat bound up in the design of Ohai. It'd be more feasible from our end to reduce memory bloat where possible but we're often at the mercy of Ruby's interaction with the system resources available. Writing the recipes to be more defensive or ensuring resource contention isn't a problem are the best ways to deal with this at present.

**Comment by tas50** [comment]
@cheeseplus Is absolutely right here. Ohai purposefully does everything it can do to never fail the overall Ohai run. A failure would result in missing data for Chef and that could have some pretty serious converge impacts during a Chef run. Sometimes it seems like Ohai should probably fail in a way that better trickle up to the user, but priority 1 always has to be providing as much data as possible to Chef.

**Comment by jaymzh** [comment]
One of the features I've wanted for a long time is the ability to mark certain plugins as critical (https://github.com/chef/ohai/issues/879) - plugins you know that without, you'll fuck your system.

**Comment by schredder** [comment]
For those who stumble upon this later, Ohai 13.6 added support to declare "critical plugins" that "will cause Ohai to fail if they don't run successfully (and thus cause a Chef run using Ohai to fail)".

See the full Chef Client 13.6.0 release notes [here](https://discourse.chef.io/t/chef-client-13-6-0-released/11843).
