### ISSUE TITLE
change dmidecode ID's to capture

### ISSUE THREAD

**Issue by bcg62** [chef/ohai#963]
I have a usecase where i would like to capture additional dmidecode output, but it seems like the ID's ohai captures are hard coded.

Is there a way to change these?
https://github.com/chef/ohai/blob/master/lib/ohai/common/dmi.rb#L74

I'd like to avoid having to write my own plugin to do the same thing with replicated code.

**Comment by tas50** [comment]
This is probably something we should allow the user to configure. I'm fairly certain this is actually a duplicate issue though since I know a few people have brought this up since we started filtering the DMI data.

**Comment by bcg62** [comment]
I tried to find issues referencing the same request but I couldn't find anything other than the comments in the code and the old ticket that created the filter

https://tickets.opscode.com/browse/OHAI-260

**Comment by tas50** [comment]
This is fixed by #970

**Comment by tas50** [comment]
In Ohai 14.1 we'll have a configuration option for additional DMI IDs to collect.
